/* =====================================================================
   Mahjong — the tile-matching solitaire, dealt winnable.

   The classic 144-tile Turtle. A tile is free when nothing rests on it
   and its left OR right flank is open; remove matching free pairs
   (flowers match any flower, seasons any season) until the desk is
   clear. Boards are generated by simulating a solve on blank tiles and
   assigning kinds to the removed pairs, so every deal can be finished.

   Coordinates: doubled grid (gx, gy) so half-step tiles (the turtle's
   head and the apex) stay integers; a tile spans 2x2 cells on layer z.
   ===================================================================== */
(function () {
  "use strict";

  function $(id) { return document.getElementById(id); }
  function fx() { return !(window.RM_ON && window.RM_ON()); }
  // a button's keycap, hidden on touch-only devices (.gs-keys, motion-toggle.js)
  function keyCap(k) { return '<span class="gs-keys"><kbd>' + k + "</kbd></span>"; }

  var store = window.GameShell ? GameShell.store : {
    get: function (k, f) { try { var v = localStorage.getItem(k); return v == null ? f : v; } catch (e) { return f; } },
    set: function (k, v) { try { localStorage.setItem(k, v); return true; } catch (e) { return false; } }
  };
  var bestTime = window.GameShell ? GameShell.best("mahjong_best_classic", { higher: false }) : null;

  function mulberry(seed) {
    var a = seed >>> 0;
    return function () {
      a |= 0; a = (a + 0x6D2B79F5) | 0;
      var t = Math.imul(a ^ (a >>> 15), 1 | a);
      t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
  }
  function shuffle(arr, rng) {
    for (var i = arr.length - 1; i > 0; i--) {
      var j = Math.floor(rng() * (i + 1)), t = arr[i]; arr[i] = arr[j]; arr[j] = t;
    }
    return arr;
  }

  // ---- daily -------------------------------------------------------------
  var DAY0 = Date.UTC(2026, 8, 27);
  function today() {
    var d = new Date();
    var utc = Date.UTC(d.getFullYear(), d.getMonth(), d.getDate());
    var n = Math.round((utc - DAY0) / 86400000) + 1;
    var mm = ("0" + (d.getMonth() + 1)).slice(-2), dd = ("0" + d.getDate()).slice(-2);
    return { n: n, ymd: d.getFullYear() + "-" + mm + "-" + dd };
  }
  function readDaily() {
    var t = today();
    try {
      var d = JSON.parse(store.get("mahjong_daily", "null"));
      if (d && d.ymd === t.ymd) return d;
    } catch (e) {}
    return { ymd: t.ymd, n: t.n, ms: 0, done: false };
  }
  function writeDaily(d) { store.set("mahjong_daily", JSON.stringify(d)); }

  // ---- the turtle -----------------------------------------------------------
  function turtlePositions() {
    var P = [], x, y;
    var rows = [[1, 12], [3, 10], [2, 11], [1, 12], [1, 12], [2, 11], [3, 10], [1, 12]];
    for (y = 0; y < 8; y++) for (x = rows[y][0]; x <= rows[y][1]; x++) P.push([x * 2, y * 2, 0]);
    P.push([0, 7, 0]);            // the head
    P.push([26, 7, 0]);           // the tail
    P.push([28, 7, 0]);           //   and its tip
    for (y = 1; y <= 6; y++) for (x = 4; x <= 9; x++) P.push([x * 2, y * 2, 1]);
    for (y = 2; y <= 5; y++) for (x = 5; x <= 8; x++) P.push([x * 2, y * 2, 2]);
    for (y = 3; y <= 4; y++) for (x = 6; x <= 7; x++) P.push([x * 2, y * 2, 3]);
    P.push([13, 7, 4]);           // the apex
    return P;                     // 144 positions
  }

  function overlaps(a, b) { return Math.abs(a[0] - b[0]) < 2 && Math.abs(a[1] - b[1]) < 2; }
  // free w.r.t. a Set of live indices into pos[]
  function isFree(pos, i, live) {
    var p = pos[i], j, q;
    var leftHit = false, rightHit = false;
    for (j = 0; j < pos.length; j++) {
      if (j === i || !live.has(j)) continue;
      q = pos[j];
      if (q[2] > p[2] && overlaps(p, q)) return false;               // capped
      if (q[2] === p[2] && Math.abs(q[1] - p[1]) < 2) {
        if (q[0] === p[0] - 2) leftHit = true;
        if (q[0] === p[0] + 2) rightHit = true;
      }
    }
    return !(leftHit && rightHit);
  }

  // ---- kinds ------------------------------------------------------------------
  var KINDS = [];
  (function () {
    var i;
    for (i = 1; i <= 9; i++) KINDS.push("d" + i);   // dots
    for (i = 1; i <= 9; i++) KINDS.push("b" + i);   // bamboo
    for (i = 1; i <= 9; i++) KINDS.push("c" + i);   // characters
    KINDS.push("wE", "wS", "wW", "wN", "dR", "dG", "dW");
  })();
  function isFlower(k) { return k[0] === "f"; }
  function isSeason(k) { return k[0] === "s"; }
  function matches(a, b) {
    if (isFlower(a) && isFlower(b)) return true;
    if (isSeason(a) && isSeason(b)) return true;
    return a === b;
  }
  function pairPool(rng) {
    var pairs = [];
    KINDS.forEach(function (k) { pairs.push([k, k], [k, k]); });      // 4 of each
    var fl = shuffle(["f1", "f2", "f3", "f4"], rng);
    var se = shuffle(["s1", "s2", "s3", "s4"], rng);
    pairs.push([fl[0], fl[1]], [fl[2], fl[3]], [se[0], se[1]], [se[2], se[3]]);
    return shuffle(pairs, rng);                                        // 72 pairs
  }

  // deal kinds onto a set of positions so a full solve exists
  function dealOnto(pos, liveIdx, kindsPairs, rng) {
    for (var attempt = 0; attempt < 200; attempt++) {
      var live = new Set(liveIdx);
      var order = [];
      var stuck = false;
      while (live.size) {
        var free = [];
        live.forEach(function (i) { if (isFree(pos, i, live)) free.push(i); });
        if (free.length < 2) { stuck = true; break; }
        shuffle(free, rng);
        var a = free[0], b = free[1];
        order.push([a, b]);
        live.delete(a); live.delete(b);
      }
      if (!stuck) {
        var kinds = {};
        order.forEach(function (pr, i) {
          kinds[pr[0]] = kindsPairs[i][0];
          kinds[pr[1]] = kindsPairs[i][1];
        });
        return kinds;
      }
    }
    return null;
  }

  // ---- tile faces (drawn once per kind at the current tile size) ---------------
  var FACES = {};
  function buildFaces(tw, th) {
    FACES = {};
    var dpr = Math.min(2, window.devicePixelRatio || 1);
    var W = Math.round(tw * dpr), H = Math.round(th * dpr);
    var RED = "#a8352a", GRN = "#3a7a3c", BLU = "#2c4a8a";
    var DOTCOL = [GRN, RED, BLU];
    function make(draw) {
      var c = document.createElement("canvas");
      c.width = W; c.height = H;
      var g = c.getContext("2d");
      g.scale(dpr, dpr);
      g.translate(tw / 2, th / 2);
      draw(g, tw, th);
      return c.toDataURL();
    }
    function ring(g, x, y, r, col) {
      g.fillStyle = col;
      g.beginPath(); g.arc(x, y, r, 0, 7); g.fill();
      g.fillStyle = "#fff";
      g.beginPath(); g.arc(x, y, r * 0.55, 0, 7); g.fill();
      g.fillStyle = col;
      g.beginPath(); g.arc(x, y, r * 0.28, 0, 7); g.fill();
    }
    // layouts of n dots in unit space (-1..1)
    var DOTPOS = {
      1: [[0, 0]],
      2: [[0, -0.55], [0, 0.55]],
      3: [[-0.6, -0.6], [0, 0], [0.6, 0.6]],
      4: [[-0.5, -0.55], [0.5, -0.55], [-0.5, 0.55], [0.5, 0.55]],
      5: [[-0.6, -0.6], [0.6, -0.6], [0, 0], [-0.6, 0.6], [0.6, 0.6]],
      6: [[-0.5, -0.6], [0.5, -0.6], [-0.5, 0], [0.5, 0], [-0.5, 0.6], [0.5, 0.6]],
      7: [[-0.6, -0.65], [0, -0.55], [0.6, -0.45], [-0.5, 0.1], [0.5, 0.1], [-0.5, 0.65], [0.5, 0.65]],
      8: [[-0.5, -0.65], [0.5, -0.65], [-0.5, -0.22], [0.5, -0.22], [-0.5, 0.22], [0.5, 0.22], [-0.5, 0.65], [0.5, 0.65]],
      9: [[-0.6, -0.6], [0, -0.6], [0.6, -0.6], [-0.6, 0], [0, 0], [0.6, 0], [-0.6, 0.6], [0, 0.6], [0.6, 0.6]]
    };
    function glyph(g, ch, col, size, y) {
      g.fillStyle = col;
      g.font = "900 " + size + "px 'Noto Serif SC', 'SimSun', serif";
      g.textAlign = "center"; g.textBaseline = "middle";
      g.fillText(ch, 0, y || 0);
    }
    function corner(g, ch, col) {
      g.fillStyle = col;
      g.font = "700 " + tw * 0.2 + "px 'Noto Serif SC', serif";
      g.textAlign = "left"; g.textBaseline = "top";
      g.fillText(ch, -tw / 2 + tw * 0.09, -th / 2 + th * 0.06);
    }
    var i;
    for (i = 1; i <= 9; i++) (function (n) {
      FACES["d" + n] = make(function (g) {
        var r = n === 1 ? tw * 0.26 : n <= 4 ? tw * 0.15 : tw * 0.115;
        DOTPOS[n].forEach(function (p, k) {
          ring(g, p[0] * tw * 0.3, p[1] * th * 0.32, r, DOTCOL[(k + n) % 3]);
        });
      });
    })(i);
    function stick(g, x, y, h2, col) {
      g.fillStyle = col;
      g.beginPath();
      if (g.roundRect) g.roundRect(x - tw * 0.05, y - h2, tw * 0.1, h2 * 2, tw * 0.05);
      else g.rect(x - tw * 0.05, y - h2, tw * 0.1, h2 * 2);
      g.fill();
      g.fillStyle = "rgba(255,255,255,0.85)";
      g.fillRect(x - tw * 0.05, y - 1, tw * 0.1, 2);
    }
    var BAMPOS = {
      2: [[0, -0.5], [0, 0.5]],
      3: [[0, -0.55], [-0.5, 0.5], [0.5, 0.5]],
      4: [[-0.45, -0.5], [0.45, -0.5], [-0.45, 0.5], [0.45, 0.5]],
      5: [[-0.55, -0.5], [0.55, -0.5], [0, 0], [-0.55, 0.5], [0.55, 0.5]],
      6: [[-0.55, -0.5], [0, -0.5], [0.55, -0.5], [-0.55, 0.5], [0, 0.5], [0.55, 0.5]],
      7: [[0, -0.62], [-0.55, 0], [0, 0], [0.55, 0], [-0.55, 0.62], [0, 0.62], [0.55, 0.62]],
      8: [[-0.55, -0.62], [0, -0.62], [0.55, -0.62], [-0.3, 0], [0.3, 0], [-0.55, 0.62], [0, 0.62], [0.55, 0.62]],
      9: [[-0.55, -0.62], [0, -0.62], [0.55, -0.62], [-0.55, 0], [0, 0], [0.55, 0], [-0.55, 0.62], [0, 0.62], [0.55, 0.62]]
    };
    FACES.b1 = make(function (g) {              // the 1-bam bird
      g.strokeStyle = GRN; g.fillStyle = GRN; g.lineWidth = 2;
      g.beginPath(); g.ellipse(0, th * 0.08, tw * 0.16, th * 0.14, 0.2, 0, 7); g.fill();
      g.beginPath(); g.arc(tw * 0.1, -th * 0.12, tw * 0.09, 0, 7); g.fill();
      g.fillStyle = RED;
      g.beginPath(); g.moveTo(tw * 0.17, -th * 0.14); g.lineTo(tw * 0.3, -th * 0.1); g.lineTo(tw * 0.17, -th * 0.07); g.closePath(); g.fill();
      g.strokeStyle = BLU;
      g.beginPath(); g.moveTo(-tw * 0.05, th * 0.2); g.quadraticCurveTo(-tw * 0.25, th * 0.3, -tw * 0.3, th * 0.14); g.stroke();
      g.beginPath(); g.moveTo(-tw * 0.02, th * 0.22); g.lineTo(-tw * 0.05, th * 0.34); g.stroke();
      g.beginPath(); g.moveTo(tw * 0.06, th * 0.22); g.lineTo(tw * 0.09, th * 0.34); g.stroke();
    });
    for (i = 2; i <= 9; i++) (function (n) {
      FACES["b" + n] = make(function (g) {
        BAMPOS[n].forEach(function (p, k) {
          stick(g, p[0] * tw * 0.32, p[1] * th * 0.3, th * 0.14, DOTCOL[(k + n) % 3]);
        });
      });
    })(i);
    var NUM = ["", "一", "二", "三", "四", "五", "六", "七", "八", "九"];
    for (i = 1; i <= 9; i++) (function (n) {
      FACES["c" + n] = make(function (g) {
        glyph(g, NUM[n], BLU, tw * 0.42, -th * 0.2);
        glyph(g, "萬", RED, tw * 0.46, th * 0.2);
      });
    })(i);
    var WINDS = { wE: "東", wS: "南", wW: "西", wN: "北" };
    Object.keys(WINDS).forEach(function (k) {
      FACES[k] = make(function (g) { glyph(g, WINDS[k], BLU, tw * 0.62); });
    });
    FACES.dR = make(function (g) { glyph(g, "中", RED, tw * 0.62); });
    FACES.dG = make(function (g) { glyph(g, "發", GRN, tw * 0.62); });
    FACES.dW = make(function (g) {
      g.strokeStyle = BLU; g.lineWidth = Math.max(2, tw * 0.06);
      g.strokeRect(-tw * 0.26, -th * 0.3, tw * 0.52, th * 0.6);
      g.lineWidth = Math.max(1, tw * 0.03);
      g.strokeRect(-tw * 0.17, -th * 0.2, tw * 0.34, th * 0.4);
    });
    var FLOW = { f1: "梅", f2: "蘭", f3: "竹", f4: "菊" };
    Object.keys(FLOW).forEach(function (k, ix) {
      FACES[k] = make(function (g) {
        glyph(g, FLOW[k], GRN, tw * 0.5, th * 0.05);
        corner(g, String(ix + 1), RED);
      });
    });
    var SEAS = { s1: "春", s2: "夏", s3: "秋", s4: "冬" };
    Object.keys(SEAS).forEach(function (k, ix) {
      FACES[k] = make(function (g) {
        glyph(g, SEAS[k], RED, tw * 0.5, th * 0.05);
        corner(g, String(ix + 1), BLU);
      });
    });
  }

  // ---- state ---------------------------------------------------------------------
  var state = "menu";                 // menu | play | over
  var mode = store.get("mahjong_mode", "classic");
  if (mode !== "classic" && mode !== "daily") mode = "classic";
  var pos = turtlePositions();
  var kinds = {}, live = new Set(), els = {};
  var selected = -1, undoStack = [], timeMs = 0, penaltyMs = 0;
  var TW = 44, TH = 58, dailyRecorded = false;

  function freeList() {
    var out = [];
    live.forEach(function (i) { if (isFree(pos, i, live)) out.push(i); });
    return out;
  }
  function freePairs() {
    var free = freeList(), out = [];
    for (var i = 0; i < free.length; i++) {
      for (var j = i + 1; j < free.length; j++) {
        if (matches(kinds[free[i]], kinds[free[j]])) out.push([free[i], free[j]]);
      }
    }
    return out;
  }

  // ---- board DOM -------------------------------------------------------------------
  function layout() {
    var vw = window.innerWidth, vh = window.innerHeight;
    var chromeTop = vw < 640 ? 96 : 56;
    TW = Math.floor(Math.min((vw - 30) / 15.6, (vh - chromeTop - 30) / 10.9));
    TW = Math.max(24, Math.min(56, TW));
    TH = Math.round(TW * 1.32);
    var zOff = Math.max(3, Math.round(TW * 0.12));
    buildFaces(TW - 4, TH - 4);
    var board = $("board");
    board.style.width = (15 * TW + 4 * zOff) + "px";
    board.style.height = (8 * TH + 4 * zOff + 8) + "px";
    Object.keys(els).forEach(function (i) {
      i = +i;
      var p = pos[i], el = els[i];
      el.style.width = (TW - 2) + "px";
      el.style.height = (TH - 2) + "px";
      el.style.left = (p[0] * TW / 2 + p[2] * zOff) + "px";
      el.style.top = (p[1] * TH / 2 - p[2] * zOff + 4) + "px";
      el.style.zIndex = p[2] * 1000 + p[0] + p[1];
      el.style.backgroundImage = "url(" + FACES[kinds[i]] + "), linear-gradient(160deg, #fdf9ee, #f8f2e2 55%, #ece2cb)";
    });
    refreshFreedom();
  }
  window.addEventListener("resize", function () { if (state !== "menu") layout(); });

  function buildBoard() {
    var board = $("board");
    board.innerHTML = "";
    els = {};
    live.forEach(function (i) {
      var b = document.createElement("button");
      b.type = "button";
      b.className = "tile";
      b.setAttribute("aria-label", "tile");
      (function (idx) { b.addEventListener("click", function () { clickTile(idx); }); })(i);
      board.appendChild(b);
      els[i] = b;
    });
    layout();
  }
  function refreshFreedom() {
    var free = new Set(freeList());
    Object.keys(els).forEach(function (i) {
      els[i].classList.toggle("free", free.has(+i));
    });
  }

  // ---- sound --------------------------------------------------------------------------
  var actx = null;
  function audio() {
    if (!actx) { var AC = window.AudioContext || window.webkitAudioContext; if (AC) actx = new AC(); }
    if (actx && actx.state === "suspended") actx.resume();
    return actx;
  }
  function clack(hi) {
    var ac = audio(); if (!ac) return;
    var t0 = ac.currentTime;
    var len = Math.floor(ac.sampleRate * 0.03), buf = ac.createBuffer(1, len, ac.sampleRate);
    var d = buf.getChannelData(0);
    for (var i = 0; i < len; i++) d[i] = (Math.random() * 2 - 1) * (1 - i / len);
    var src = ac.createBufferSource(); src.buffer = buf;
    var bp = ac.createBiquadFilter(); bp.type = "bandpass"; bp.frequency.value = hi ? 2600 : 1500; bp.Q.value = 2;
    var g = ac.createGain(); g.gain.value = 0.3;
    src.connect(bp); bp.connect(g); g.connect(ac.destination); src.start(t0);
  }
  function thunk() {
    var ac = audio(); if (!ac) return;
    var t0 = ac.currentTime, o = ac.createOscillator(), g = ac.createGain();
    o.type = "sine"; o.frequency.setValueAtTime(160, t0);
    o.frequency.exponentialRampToValueAtTime(90, t0 + 0.08);
    g.gain.setValueAtTime(0.12, t0);
    g.gain.exponentialRampToValueAtTime(0.0001, t0 + 0.1);
    o.connect(g); g.connect(ac.destination); o.start(t0); o.stop(t0 + 0.12);
  }
  function chime() {
    var ac = audio(); if (!ac) return;
    [660, 880, 1174].forEach(function (f, i) {
      var t0 = ac.currentTime + i * 0.1;
      var o = ac.createOscillator(), g = ac.createGain();
      o.type = "triangle"; o.frequency.value = f;
      g.gain.setValueAtTime(0.1, t0);
      g.gain.exponentialRampToValueAtTime(0.0001, t0 + 0.5);
      o.connect(g); g.connect(ac.destination); o.start(t0); o.stop(t0 + 0.55);
    });
  }

  // ---- play -----------------------------------------------------------------------------
  function clickTile(i) {
    if (state !== "play" || !live.has(i)) return;
    if (!isFree(pos, i, live)) {
      var el = els[i];
      el.classList.remove("shake"); void el.offsetWidth; el.classList.add("shake");
      // FX off shows .shake as a held red edge (styles.css), so a timer takes it off
      clearTimeout(el.shakeT);
      el.shakeT = setTimeout(function () { el.classList.remove("shake"); }, 450);
      thunk();
      return;
    }
    if (selected === i) { els[i].classList.remove("sel"); selected = -1; return; }
    if (selected >= 0 && matches(kinds[selected], kinds[i])) {
      removePair(selected, i);
      return;
    }
    if (selected >= 0) els[selected].classList.remove("sel");
    selected = i;
    els[i].classList.add("sel");
    clack(true);
  }
  function removePair(a, b) {
    els[a].classList.remove("sel");
    live.delete(a); live.delete(b);
    els[a].remove(); els[b].remove();
    delete els[a]; delete els[b];
    undoStack.push([a, b]);
    selected = -1;
    clack(false);
    refreshFreedom();
    hud();
    if (!live.size) { win(); return; }
    if (!freePairs().length) hint(true);   // nudge: no moves — suggests shuffle
  }
  function undo() {
    if (state !== "play" || !undoStack.length) return;
    var pr = undoStack.pop();
    penaltyMs += 15000;
    dead = false;                      // a pair back on the board: there's a way on again
    pr.forEach(function (i) {
      live.add(i);
      var b = document.createElement("button");
      b.type = "button"; b.className = "tile";
      (function (idx) { b.addEventListener("click", function () { clickTile(idx); }); })(i);
      $("board").appendChild(b);
      els[i] = b;
    });
    if (selected >= 0) { els[selected] && els[selected].classList.remove("sel"); selected = -1; }
    layout();
    hud();
    clack(true);
  }
  function hint(isNudge) {
    if (state !== "play") return;
    var prs = freePairs();
    if (!prs.length) {
      // nothing matches: point at the shuffle, or at Undo when no reshuffle
      // can fit what's left (a lone stack, say)
      if (redeal()) pointAt("btn-shuffle");
      else noRedeal();
      if (!isNudge) thunk();
      return;
    }
    if (!isNudge) penaltyMs += 30000;
    var pr = prs[Math.floor(Math.random() * prs.length)];
    pr.forEach(function (i) {
      var el = els[i];
      el.classList.remove("hintg"); void el.offsetWidth; el.classList.add("hintg");
      // FX off holds the glow still (styles.css): it comes off once the two
      // 0.8s pulses would have finished
      clearTimeout(el.hintT);
      el.hintT = setTimeout(function () { el.classList.remove("hintg"); }, 1650);
    });
    hud();
  }
  // a HUD button outlined for a moment: "try this"
  function pointAt(id) {
    var b = $(id);
    b.style.outline = "3px solid #ffd23f";
    clearTimeout(b.pointT);
    b.pointT = setTimeout(function () { b.style.outline = ""; }, 1200);
  }
  // the remaining kinds regrouped into matchable pairs and re-dealt solvably
  // onto the same spots; null when no solvable deal fits them
  function redeal() {
    var rem = [];
    live.forEach(function (i) { rem.push(kinds[i]); });
    var groups = {};
    rem.forEach(function (k) {
      var g = isFlower(k) ? "F" : isSeason(k) ? "S" : k;
      (groups[g] = groups[g] || []).push(k);
    });
    var pairs = [];
    Object.keys(groups).forEach(function (g) {
      var arr = groups[g];
      for (var i = 0; i + 1 < arr.length; i += 2) pairs.push([arr[i], arr[i + 1]]);
    });
    var rng = Math.random;
    shuffle(pairs, rng);
    return dealOnto(pos, [...live], pairs, rng);
  }
  // no reshuffle fits: the board is dead. Taking a pair back is the way on;
  // the HUD offers a new deal too (hud())
  function noRedeal() {
    dead = true;
    pointAt("btn-undo");
    hud();
  }
  function reshuffle() {
    if (state !== "play" || (live.size < 4 && freePairs().length)) return;
    var dealt = redeal();
    if (!dealt) {
      // the board stays, and it costs nothing
      thunk();
      noRedeal();
      return;
    }
    penaltyMs += 60000;
    kinds = Object.assign({}, kinds, dealt);
    if (selected >= 0 && els[selected]) els[selected].classList.remove("sel");   // its face just changed
    selected = -1;
    layout();
    hud();
    clack(false);
  }

  // ---- runs ------------------------------------------------------------------------------
  function startRun(m) {
    if (m) mode = m;
    store.set("mahjong_mode", mode);
    audio();
    var rng = mode === "daily" ? mulberry(((today().n * 2654435761) >>> 0) ^ 0x3A7) : mulberry((Math.random() * 0xffffffff) >>> 0);
    live = new Set(pos.map(function (_, i) { return i; }));
    kinds = dealOnto(pos, [...live], pairPool(rng), rng);
    dailyRecorded = mode === "daily" ? readDaily().done : false;
    selected = -1; undoStack = []; timeMs = 0; penaltyMs = 0; dead = false;
    $("menu").hidden = true; $("over").hidden = true; $("hudline").hidden = false;
    state = "play";
    buildBoard();
    hud();
  }
  function fmt(ms) {
    var s = Math.floor(ms / 1000);
    return Math.floor(s / 60) + ":" + ("0" + (s % 60)).slice(-2);
  }
  // a dead board (no pairs, and no reshuffle fits): until a pair is taken back
  // or a new deal starts, the HUD says so in place of the pairs count and
  // offers the ways out after Undo: New deal, and on the Daily, giving up
  var dead = false;
  function hud() {
    $("hud-time").textContent = fmt(timeMs + penaltyMs);
    $("hud-left").textContent = live.size + " tiles";
    $("hud-pairs").textContent = dead ? "no reshuffle fits — undo a pair, or" : freePairs().length + " pairs open";
    $("hud-stuck").hidden = !dead;
    $("btn-giveup").hidden = mode !== "daily";
  }
  function win() {
    state = "over";
    chime();
    var total = timeMs + penaltyMs;
    var lines = [], isBest = false;
    if (mode === "daily") {
      var d = readDaily();
      if (!d.done) { d.done = true; d.ms = total; writeDaily(d); }
      var rec = readDaily();
      $("over-title").textContent = "The desk is clear";
      $("over-msg").textContent = fmt(total);
      lines.push("Daily turtle No. " + rec.n +
        (dailyRecorded ? " — recorded earlier: " + fmt(rec.ms) : ""));
      $("share").hidden = false;
      $("again").innerHTML = "Once more (just for fun) " + keyCap("Enter");
    } else {
      isBest = bestTime ? bestTime.submit(Math.round(total)) : false;
      $("over-title").textContent = "The desk is clear";
      $("over-msg").textContent = fmt(total);
      lines.push(isBest ? "a new fastest clear! 🀄" :
        "best: " + (bestTime && bestTime.get() ? fmt(bestTime.get()) : fmt(total)));
      $("share").hidden = true;
      $("again").innerHTML = "Deal again " + keyCap("Enter");
    }
    $("over-stats").textContent = lines.join("\n");
    $("hudline").hidden = true;
    $("over").hidden = false;
  }
  function shareDaily() {
    var d = readDaily();
    var text = "Mahjong · Daily turtle No. " + d.n + " (" + d.ymd + ")\n" +
      "Cleared in " + fmt(d.ms) + " 🀄\n" + location.origin + location.pathname;
    function copied() { $("share").textContent = "copied!"; setTimeout(function () { $("share").textContent = "Share result"; }, 1400); }
    // (the clipboard wasn't allowed: show the result to copy, in the game's own look)
    function fallback() { if (window.GameShell) GameShell.copyBox({ title: "Copy your result", text: text }); else try { window.prompt("Copy your result:", text); } catch (e) {} }
    if (navigator.share && /Mobi|Android|iPhone|iPad/.test(navigator.userAgent)) {
      navigator.share({ text: text }).catch(function (e2) { if (!e2 || e2.name !== "AbortError") fallback(); });
      return;
    }
    if (navigator.clipboard && navigator.clipboard.writeText) navigator.clipboard.writeText(text).then(copied, fallback);
    else fallback();
  }

  // the clock
  var P = window.GameShell ? GameShell.pausable({
    canPause: function () { return state === "play"; },
    keys: ["Escape", "p"]
  }) : { isPaused: function () { return false; } };
  // Leaving asks first once the desk has been played (a pair taken, or a hint,
  // undo or shuffle's penalty), paused included, pausing through P; a fresh
  // deal loses nothing even with its clock running
  if (window.GameShell) GameShell.guardLeave({
    active: function () { return state === "play" && (undoStack.length > 0 || penaltyMs > 0); },
    pausable: P
  });
  setInterval(function () {
    if (state !== "play" || P.isPaused()) return;
    timeMs += 200;
    hud();
  }, 200);
  // follow the ✨ switch the moment it flips (this used to poll every 400ms)
  window.addEventListener("reducemotionchange", function () { document.body.classList.toggle("fxon", fx()); });
  document.body.classList.toggle("fxon", fx());

  // ---- menu -------------------------------------------------------------------------------
  function paintMenu() {
    document.querySelectorAll("#pick-mode button").forEach(function (b) {
      b.classList.toggle("on", b.getAttribute("data-v") === mode);
    });
    var d = readDaily();
    $("daily-small").innerHTML = d.done
      ? "done: " + fmt(d.ms) + " ✓ " + keyCap("2")
      : "today's turtle, shareable " + keyCap("2");
    $("bests").textContent = bestTime && bestTime.get()
      ? "fastest clear: " + fmt(bestTime.get())
      : "no cleared desks yet";
  }
  function toMenu() {
    state = "menu";
    $("over").hidden = true; $("hudline").hidden = true;
    $("board").innerHTML = "";
    $("menu").hidden = false;
    paintMenu();
  }
  document.querySelectorAll("#pick-mode button").forEach(function (b) {
    b.addEventListener("click", function () {
      mode = b.getAttribute("data-v");
      store.set("mahjong_mode", mode);
      paintMenu();
    });
    // a mouse click doesn't take focus (Tab still reaches it): left focused,
    // the Enter that should deal would press the mode again
    b.addEventListener("mousedown", function (e) { e.preventDefault(); });
  });
  $("play").addEventListener("click", function () { startRun(mode); });
  $("again").addEventListener("click", function () { startRun(mode); });
  $("to-menu").addEventListener("click", toMenu);
  $("share").addEventListener("click", shareDaily);
  $("btn-hint").addEventListener("click", function () { hint(false); });
  $("btn-undo").addEventListener("click", undo);
  $("btn-shuffle").addEventListener("click", reshuffle);
  // the ways off a dead board after Undo, asking first while the desk has
  // been played (the leave guard below). The Daily keeps only a clear, so
  // giving it up records nothing and today's turtle stays open.
  function ask(opts, go) {
    if (window.GameShell && GameShell.askQuit) GameShell.askQuit(opts, go);
    else go();
  }
  // (on the Daily a new deal is today's turtle again: a start over)
  $("btn-newdeal").addEventListener("click", function () {
    ask(mode === "daily"
      ? { title: "Start over?", ok: "Start over", text: "Today's turtle is dealt again, from the start." }
      : { title: "Start a new game?", ok: "New game" },
      function () { startRun(mode); });
  });
  $("btn-giveup").addEventListener("click", function () {
    ask({ title: "Quit this game?", ok: "Quit", text: "Today's turtle isn't recorded, and stays open for another try." }, toMenu);
  });

  document.addEventListener("keydown", function (e) {
    if (P.isPaused()) return;          // paused: no play keys, Ctrl+Z's undo included
    if (e.ctrlKey || e.metaKey || e.altKey) {
      if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === "z" && state === "play") { e.preventDefault(); undo(); }
      return;
    }
    if (e.repeat) return;
    if (state === "play") {
      var k = e.key.toLowerCase();
      if (k === "h") hint(false);
      else if (k === "u") undo();
      else if (k === "s") reshuffle();
      return;
    }
    // Enter on a focused button is that button's click (a mode, Share, Modes…);
    // dealing here as well would run both
    if (e.key === "Enter" && e.target && e.target.closest && e.target.closest("button")) return;
    if (state === "menu") {
      if (e.key === "1" || e.key === "2") {
        mode = e.key === "1" ? "classic" : "daily";
        store.set("mahjong_mode", mode);
        paintMenu();
      } else if (e.key === "Enter") startRun(mode);
      return;
    }
    // Backspace goes back to the modes (Esc is left to ../motion-toggle.js,
    // which takes it to the games page)
    if (state === "over") {
      if (e.key === "Enter") startRun(mode);
      else if (e.key === "Backspace") { e.preventDefault(); toMenu(); }
    }
  });

  toMenu();

  // test hooks — the Playwright harness drives runs through these
  window.Mahjong = {
    state: function () { return state; },
    tilesLeft: function () { return live.size; },
    freePairsCount: function () { return freePairs().length; },
    removeOnePair: function () {
      var prs = freePairs();
      if (!prs.length) return false;
      removePair(prs[0][0], prs[0][1]);
      return true;
    },
    kindCounts: function () {
      var c = {};
      live.forEach(function (i) { c[kinds[i]] = (c[kinds[i]] || 0) + 1; });
      return c;
    },
    boardHash: function () {
      var s = [];
      live.forEach(function (i) { s.push(i + ":" + kinds[i]); });
      return s.sort().join("|");
    },
    tileRect: function (i) { return els[i] ? els[i].getBoundingClientRect() : null; },
    freeIdx: function () { return freeList(); },
    kindOf: function (i) { return kinds[i]; },
    click: clickTile,
    undoNow: undo,
    shuffleNow: reshuffle,
    hintNow: function () { hint(false); },
    timeNow: function () { return timeMs + penaltyMs; },
    daily: readDaily,
    start: startRun,
    toMenu: toMenu
  };
})();
