/* =====================================================================
   Slither — Labyrinth levels.

   Each level: { id, zone, name, hint, time (seconds; 0 = untimed), grid }
   plus optional speed (ms per cell), spikeMs, enemyMs ({ hunt: 230 }).
   `id` keys saved best times, so never reuse or rename one. Every grid row
   must be the same width. The tile legend is at the top of
   labyrinth-engine.js. Run `node verify.js` after editing: it proves each
   level can be finished and checks the time limits.

   Spike levels keep spikeMs a whole number of 135 ms steps (1080 = 8,
   1350 = 10) so the checker can time them exactly.
   ===================================================================== */
(function (root, factory) {
  var mod = factory();
  if (typeof module !== "undefined" && module.exports) module.exports = mod;
  if (typeof window !== "undefined") window.SLITHER_LEVELS = mod;
})(this, function () {
  "use strict";

  return [
    // ------------------------------------------------------------ Garden
    {
      id: "first-bite", zone: "Garden", name: "First Bite", time: 30,
      hint: "Eat every 🍎, then slither into the arch. It stays locked — and solid — until the last apple is gone.",
      grid: [
        "####################",
        "#..................#",
        "#..a...........a...#",
        "#..................#",
        "#..................#",
        "#...S..........E...#",
        "#..................#",
        "#..................#",
        "#.........a........#",
        "#..................#",
        "#..................#",
        "####################",
      ],
    },
    {
      id: "zig-zag", zone: "Garden", name: "Zig Zag", time: 26,
      hint: "Hold Shift (or ⚡) to dash. The clock is tight — the straightaways are where you win time back.",
      grid: [
        "########################",
        "#S.........a...........#",
        "#####################..#",
        "#......a...............#",
        "#..#####################",
        "#...............a......#",
        "#####################..#",
        "#.........a............#",
        "#..#####################",
        "#..........a...........#",
        "#####################..#",
        "#E.....................#",
        "########################",
      ],
    },
    {
      id: "wormholes", zone: "Garden", name: "Wormholes", time: 30,
      hint: "Portals come in matching pairs. Dive into one and pop out of its twin, still heading the same way.",
      grid: [
        "####################",
        "#........#.........#",
        "#..a.....#....a....#",
        "#........#.........#",
        "#....1...#...1.....#",
        "#........#.........#",
        "#..S.....#.....E...#",
        "#........#.........#",
        "#....2...#...2.....#",
        "#..a.....#.....a...#",
        "#........#.........#",
        "####################",
      ],
    },
    {
      id: "thin-ice", zone: "Garden", name: "Thin Ice", time: 40,
      hint: "You can't turn on ice — line up before you step on. Apples are solid ground, and queued turns fire once you slide off.",
      grid: [
        "########################",
        "#S.....................#",
        "#......................#",
        "#..####.########.####..#",
        "#..#~~~~~~~~~~~~~~~~#..#",
        "#..#~~~~~~~~~~~~~~~~#..#",
        "#...~~~a~~~~~~~~a~~~...#",
        "#..#~~~~~~~~~~~~~~~~#..#",
        "#..#~~~~~~~~~~~~~~~~#..#",
        "#..####.########.####..#",
        "#......................#",
        "#..a..........E......a.#",
        "########################",
      ],
    },
    {
      id: "phantom", zone: "Garden", name: "Phantom", time: 30,
      hint: "Eat a 👻 apple, then hold G or right-click (or 👻 on touch) to phase through walls. Let go before the arch — ghosts can't leave.",
      grid: [
        "####################",
        "#..................#",
        "#..S..........g....#",
        "#..................#",
        "#.......########...#",
        "#.......#..a...#...#",
        "#..g....#..E...#...#",
        "#.......#...a..#...#",
        "#.......########...#",
        "#..................#",
        "#..................#",
        "####################",
      ],
    },
    {
      id: "blink", zone: "Garden", name: "Blink", time: 40,
      hint: "Eat a ✦ apple, then click (or tap) any open cell to blink your head there. The vault has no door.",
      grid: [
        "########################",
        "#......................#",
        "#.S..........a.........#",
        "#......................#",
        "#.......#########......#",
        "#...t...#.......#......#",
        "#.......#...a...#...a..#",
        "#.......#.......#......#",
        "#.......#...E...#......#",
        "#.......#########......#",
        "#......................#",
        "#......................#",
        "########################",
      ],
    },
    {
      id: "switchback", zone: "Garden", name: "Switchback", time: 45,
      hint: "Roll over a switch to flip every door: shut ones open, open ones shut.",
      grid: [
        "########################",
        "#S.........#.....#.....#",
        "#..........#.....#..E..#",
        "#..a.......#..a..#.....#",
        "#..........#......##d###",
        "#..........#...........#",
        "#..........D...........#",
        "#..........#...........#",
        "#..........#...........#",
        "#....k.....#..k........#",
        "#......a...#...a....$..#",
        "#..........#...........#",
        "########################",
      ],
    },
    {
      id: "patrol", zone: "Garden", name: "Patrol", time: 50,
      hint: "Red loopers keep a wall on their right and circle forever. Every apple sits on a loop — time your dash between them.",
      grid: [
        "########################",
        "#......................#",
        "#...........a..........#",
        "#....R..........R......#",
        "#....###........###....#",
        "#....###........###....#",
        "#.....a....R.....a.....#",
        "#..........###.........#",
        "#..........###.........#",
        "#...........a..........#",
        "#......................#",
        "#S....................E#",
        "########################",
      ],
    },
    {
      id: "the-hunt", zone: "Garden", name: "The Hunt", time: 50, enemyMs: { hunt: 230 },
      hint: "Purple hunters try to cut you off. If your head hits them you crash — if theirs hits you, they pop.",
      grid: [
        "########################",
        "#..........+...........#",
        "#.a..................a.#",
        "#......................#",
        "#....##..........##....#",
        "#....##..........##....#",
        "#..........S...........#",
        "#......................#",
        "#..........E...........#",
        "#....##..........##....#",
        "#....##..........##....#",
        "#......................#",
        "#.a..................a.#",
        "#.....................H#",
        "########################",
      ],
    },

    // ------------------------------------------------------------ Ruins
    {
      id: "spike-walk", zone: "Ruins", name: "Spike Walk", time: 45, spikeMs: 1080,
      hint: "Spikes rise and fall on a beat and flash red just before rising. ^ and v rows move in opposite beats. Raised spikes cut any part of you.",
      grid: [
        "########################",
        "#S.........a...........#",
        "#......................#",
        "#......................#",
        "#^^^^^^^^^^^^^^^^^^^^^^#",
        "#......................#",
        "#....a...........a.....#",
        "#......................#",
        "#vvvvvvvvvvvvvvvvvvvvvv#",
        "#......................#",
        "#..........E...........#",
        "#......................#",
        "########################",
      ],
    },
    {
      id: "shortcut", zone: "Ruins", name: "Shortcut", time: 0, spikeMs: 1080,
      warps: ["lights-out"],
      hint: "No clock here. A violet arch behind the spike gate skips you two levels ahead; both arches open once the apples are gone.",
      grid: [
        "########################",
        "#S.....................#",
        "#..a..............a....#",
        "#......................#",
        "#.......########.......#",
        "#.......#..Q...#.......#",
        "#.......#......#.......#",
        "#.......###^^###.......#",
        "#......................#",
        "#..a..............a....#",
        "#......................#",
        "#...........E..........#",
        "########################",
      ],
    },
    {
      id: "haircut", zone: "Ruins", name: "Haircut", time: 55, spikeMs: 1080,
      hint: "✂ trims you back to three segments. A long snake can't clear the spikes in one beat.",
      grid: [
        "########################",
        "#S..a....a....a....a...#",
        "#......................#",
        "#..a....a....a....a....#",
        "#......................#",
        "#####.############.#####",
        "#.................x....#",
        "#......................#",
        "#^^^^^^^^^^^^^^^^^^^^^^#",
        "#......................#",
        "#..a.......E........a..#",
        "#......................#",
        "########################",
      ],
    },
    {
      id: "wanderers", zone: "Ruins", name: "Wanderers", time: 50,
      hint: "Blue wanderers roam at random. They eat apples too — and every apple they eat still counts toward the exit.",
      grid: [
        "########################",
        "#S..........$..........#",
        "#..a.......W.......a...#",
        "#......................#",
        "#...##....####....##...#",
        "#...##....####....##...#",
        "#......a..####...a.....#",
        "#...##....####....##...#",
        "#...##....####....##...#",
        "#......................#",
        "#..a.......W.......a.W.#",
        "#...........E..........#",
        "########################",
      ],
    },
    {
      id: "lights-out", zone: "Ruins", name: "Lights Out", time: 50,
      hint: "In the dark you can't see yourself — only the walls and the apples. Count your turns.",
      grid: [
        "########################",
        "#S........a............#",
        "#......................#",
        "#::::::::::::::::::::::#",
        "#::::##::::::::::##::::#",
        "#::a:##:::::a::::##::a:#",
        "#::::##::::::::::##::::#",
        "#::::::::::####::::::::#",
        "#::::::a:::####:::a::::#",
        "#::::::::::::::::::::::#",
        "#......................#",
        "#..........E...........#",
        "########################",
      ],
    },
    {
      id: "melon-patch", zone: "Ruins", name: "Melon Patch", time: 70,
      unproven: "the munchers have to eat the watermelons first",
      hint: "Watermelons are walls to you, but munchers love them. Keep the munchers alive and let them chew a way through to the exit.",
      grid: [
        "########################",
        "#......................#",
        "#..a...................#",
        "#...........M.....######",
        "#.......a.........#....#",
        "#.............#####....#",
        "#.S............mmm...E.#",
        "#.............#####....#",
        "#.................#....#",
        "#........a..M.....######",
        "#...a..................#",
        "#......................#",
        "########################",
      ],
    },
    {
      id: "zoomies", zone: "Ruins", name: "Zoomies", time: 30,
      hint: "Every 🍏 makes you faster, for good. How fast can you go?",
      grid: [
        "########################",
        "#S.f.f.f.f.a.f.f.f.f...#",
        "#......................#",
        "#..##################..#",
        "#f.#................#.f#",
        "#..#................#..#",
        "#a.#......E....+....#.a#",
        "#..#................#..#",
        "#f.#................#.f#",
        "#..#########.########..#",
        "#......................#",
        "#...f.f.f.a.f.f.f.f....#",
        "########################",
      ],
    },
    {
      id: "wormhole-maze", zone: "Ruins", name: "Wormhole Maze", time: 40,
      hint: "Four rooms and no doors. Every portal pair links two of them.",
      grid: [
        "########################",
        "#S.........#...........#",
        "#....a.....#........2..#",
        "#.......1..#.....a.....#",
        "#..4.......#..1........#",
        "#..........#...........#",
        "########################",
        "#..........#...........#",
        "#..4.......#.....E.....#",
        "#.......3..#........2..#",
        "#....a.....#..3........#",
        "#..........#...........#",
        "########################",
      ],
    },
    {
      id: "red-line", zone: "Ruins", name: "Red Line", time: 60, teleReverse: "8",
      hint: "Red pads only work one way. Four sealed rooms, one route — and the pad to the exit room has no way back.",
      grid: [
        "########################",
        "#..8.......##..........#",
        "#........5.##.......a..#",
        "#.S........##..........#",
        "#.....a....##.5......6.#",
        "#..........##..........#",
        "########################",
        "#..........##..........#",
        "#.6......7.##..........#",
        "#..........##.7......E.#",
        "#.8.....a..##..........#",
        "#..........##..........#",
        "########################",
      ],
    },

    // ------------------------------------------------------------ Citadel
    {
      id: "floodgates", zone: "Citadel", name: "Floodgates", time: 60,
      hint: "Every switch flips every door. Press each one once — and only once.",
      grid: [
        "########################",
        "########################",
        "#S...#....#....#....#..#",
        "#....#..a.#....#.a..#.$#",
        "#..a.#....#....#....#..#",
        "#....#....#..a.#....#..#",
        "#....D....d....D....d.E#",
        "#....#....#....#....#..#",
        "#....#.k..#..k.#.k..#..#",
        "#.k..#....#....#....#..#",
        "#....#....#....#....#..#",
        "########################",
        "########################",
      ],
    },
    {
      id: "chroma-lock", zone: "Citadel", name: "Chroma Lock", time: 90,
      hint: "Each vault door has a twin on the exit corridor: open one and the other shuts. Square switches flip when you click them (or press 1 / 2); round ones when you roll over them.",
      grid: [
        "########################",
        "#......#.......#.......#",
        "#..a...#...a...#...a...#",
        "#......#..o....#.......#",
        "#......#.......#.......#",
        "###D#######C#######P####",
        "#......................#",
        "#.S....................#",
        "#....K.......N.........#",
        "#..................o...#",
        "####################.###",
        "####################.###",
        "###E....p...c...d....###",
        "########################",
      ],
    },
    {
      id: "ghost-lanes", zone: "Citadel", name: "Ghost Lanes", time: 60,
      hint: "Green ghosts glide straight through walls and wrap around the edges. They can't be hurt — and you can't pass through them. Watch the lanes, then cross.",
      grid: [
        "########################",
        "#......L.a.##........E.#",
        "#..........##..........#",
        "#G.....................#",
        "#..........##..........#",
        "#...a......##.a........#",
        "###.################.###",
        "#..........##...L......#",
        "#..........##..........#",
        "#............G.........#",
        "#.S........##..........#",
        "#........a.##........a.#",
        "########################",
      ],
    },
    {
      id: "cheese", zone: "Citadel", name: "Cheese", time: 40,
      hint: "Pink Mouse Eaters chase your pointer — if one catches it, your teleport, ghost and click-switches stall for 6 s. Park the pointer where they can't reach, like inside a sealed vault.",
      grid: [
        "########################",
        "#S..........V..........#",
        "#......................#",
        "#..######......######..#",
        "#..#....#......#....#..#",
        "#..#.at.#......#.at.#..#",
        "#..#....#..a...#....#..#",
        "#..######......######..#",
        "#......................#",
        "#......................#",
        "#.t....................#",
        "#..........V..........E#",
        "########################",
      ],
    },
    {
      id: "blink-chain", zone: "Citadel", name: "Blink Chain", time: 50,
      hint: "Each vault hides the key to the next — and the last one has no way out. One blink per ✦, so clean up outside first.",
      grid: [
        "########################",
        "#......................#",
        "#......................#",
        "#.######.######.######.#",
        "#.#a..t#.#a..t#.#a...#.#",
        "#.#....#.#....#.#..E.#.#",
        "#.#....#.#....#.#....#.#",
        "#.######.######.######.#",
        "#......................#",
        "#..S......t.......a....#",
        "#....a.................#",
        "#......................#",
        "########################",
      ],
    },
    {
      id: "munch-race", zone: "Citadel", name: "Munch Race", time: 45,
      hint: "Orange munchers race you for apples — every apple they eat still counts. Their growing bodies are the real problem. 👻 passes through bodies.",
      grid: [
        "########################",
        "#S.....a.......a.....M.#",
        "#..a.........g.......a.#",
        "#..##..##..##..##..##..#",
        "#..##..##..##..##..##..#",
        "#a.....a...........a...#",
        "#..........aE..........#",
        "#..##..##..##..##..##..#",
        "#..##..##..##..##..##..#",
        "#M..a.......g.....a....#",
        "#.......a...........a.$#",
        "#..........M...........#",
        "########################",
      ],
    },
    {
      id: "mirror-mirror", zone: "Citadel", name: "Mirror, Mirror", time: 60,
      hint: "Pale copycats turn whenever you turn. Lead them into the walls — or they'll box you in.",
      grid: [
        "########################",
        "#...........a..........#",
        "#..a.................J.#",
        "#.....##........##.....#",
        "#.....##........##.....#",
        "#......................#",
        "#...a.......S......a..E#",
        "#......................#",
        "#.....##........##.....#",
        "#.....##........##.....#",
        "#.J.................a..#",
        "#...........J..........#",
        "########################",
      ],
    },
    {
      id: "spike-gauntlet", zone: "Citadel", name: "Spike Gauntlet", time: 70, spikeMs: 1080,
      hint: "Circle until a gate drops, then go. Your whole length has to clear the spikes inside one beat — ✂ helps.",
      grid: [
        "########################",
        "#S.....a........a......#",
        "#......................#",
        "#..........a...........#",
        "####################^^##",
        "#......................#",
        "#....a.......x.....a...#",
        "#......................#",
        "##vv####################",
        "#......................#",
        "#...a......a.......a...#",
        "#......................#",
        "###########^^###########",
        "###########^^###########",
        "#..........E...........#",
        "########################",
      ],
    },
    {
      id: "dark-hunt", zone: "Citadel", name: "Dark Hunt", time: 60,
      hint: "Snakes vanish in the dark — yours and theirs. Watch where they went in.",
      grid: [
        "########################",
        "#S....::::.....::::....#",
        "#..a..::::..a..::::.a..#",
        "#.....:a::.....::a:....#",
        "#.....::::.....::::....#",
        "#.....::::.....::::....#",
        "#..a..::::..E..::::.a..#",
        "#.....::::.....::::....#",
        "#.....::::.....::::....#",
        "#..a..:a::..H..::a:..a.#",
        "#.....::::.....::::....#",
        "#W....::::.....::::....#",
        "########################",
      ],
    },
    {
      id: "the-citadel", zone: "Citadel", name: "The Citadel", time: 75, spikeMs: 1350,
      hint: "Everything you've learned. The keep's door answers to a switch somewhere past the spikes.",
      grid: [
        "########################",
        "#~~~1~~~#..E...#..a.2..#",
        "#~~~a~~~#......#.......#",
        "#~~~~~~~#...a..#^^^^^^^#",
        "#~~~~~~~#......#.....+.#",
        "#~~~~~~~#......#...k...#",
        "####.######D#######.####",
        "#......................#",
        "#..a...##......##...a..#",
        "#......##..g...##......#",
        "#......................#",
        "#.H....................#",
        "#...........S.......1..#",
        "#..a.........2......a..#",
        "########################",
      ],
    },
    {
      id: "endless", zone: "Foundry", name: "Endless", time: 50, spikeMs: 1080,
      hint: "The Infinity machine makes you grow every single move. Reach a cutter ✂ before you run out of room.",
      grid: [
        "########################",
        "#S..I....a.............#",
        "#####################..#",
        "#.............a........#",
        "#..#####################",
        "#......................#",
        "#...................x..#",
        "#......................#",
        "#......................#",
        "#............####^^#####",
        "#.......a....#.........#",
        "#............#.......E.#",
        "########################",
      ],
    },
    {
      id: "iron-herd", zone: "Foundry", name: "Iron Herd", time: 60, spikeMs: 1080,
      hint: "Grey metal snakes shrug off spikes; brown drifters go straight until blocked, then turn right. The yellow zipper is just fast.",
      grid: [
        "########################",
        "#S.....................#",
        "#.........a.......a....#",
        "#...B..................#",
        "#......................#",
        "#...^^^^^^^^^^^^^^^^...#",
        "#.....A.....a..A.......#",
        "#...vvvvvvvvvvvvvvvv...#",
        "#...........$..........#",
        "#...............a......#",
        "#....a......Y........B.#",
        "#.....................E#",
        "########################",
      ],
    },
    {
      id: "double-take", zone: "Foundry", name: "Double Take", time: 70,
      unproven: "your twin has to eat the apples in the sealed room",
      proof: "0 1 0 0 0 0 0 0 0 0 3 2 2 1 2 2 1 1 1 2 2 2 1 0 0 0 1 1 1 1 0 0 0 0 3 0 1 1",
      hint: "Roll over the Cloner and a twin appears in the sealed room next door — it obeys your every turn. Its apples count too, so steer for both of you.",
      grid: [
        "########################",
        "#..#.......E#..#.......#",
        "#a.#........#..#.....a.#",
        "#..#.##.....#..#.##....#",
        "#..#.##.....#..#.##....#",
        "#..#........#..#.......#",
        "#.Z.........#.z.......a#",
        "#..#........#..#.......#",
        "#..#...##...#..#...##..#",
        "#..#...##...#..#.a.##..#",
        "#.a#........#..#.......#",
        "#S.#........#..#.......#",
        "########################",
      ],
    },
    {
      id: "stud-gates", zone: "Foundry", name: "Stud Gates", time: 45,
      hint: "Bronze studs flip every spike field at once; there's no beat here. Never press one while any part of you lies across a gate that's about to rise.",
      grid: [
        "########################",
        "#S......#.a.....#......#",
        "#...a...#.......#..a...#",
        "#.......#.......#......#",
        "#.......^.......v......#",
        "#...*...^..*....v....E.#",
        "#.......^.......v......#",
        "#.......#.......#......#",
        "#.......#.......#......#",
        "#..a....#....a..#...a..#",
        "#.......#.......#......#",
        "#.......#...$...#......#",
        "########################",
      ],
    },
    {
      id: "press-line", zone: "Foundry", name: "Press Line", time: 60,
      hint: "Three spike gates and a stud in each yard. Each stud sits just past a gate: loop round (or use the cutter) so your tail is clear before you press it. Metal snakes don't care about spikes.",
      grid: [
        "########################",
        "#S....#.....#.....#....#",
        "#.....#..a..#.....#..E.#",
        "#..a..#.....#..a..#....#",
        "#.....^.....v.....^....#",
        "#..*..^.*...v.*...^....#",
        "#.....^.....v.....^....#",
        "#.....#.....#.....#..a.#",
        "#.....#..A..#..x..#....#",
        "#..a..#.....#.....#....#",
        "#.....#..a..#..a..#.A..#",
        "#.....#.....#.....#....#",
        "########################",
      ],
    },
    {
      id: "switchyard", zone: "Foundry", name: "Switchyard", time: 60,
      hint: "The amber switch is caged in spikes, and the stud that sinks the cage also raises the fence behind you. Work out the order.",
      grid: [
        "########################",
        "#S.......v.........a...#",
        "#........v.............#",
        "#..a.....v.....^^^^^...#",
        "#........v.....^.k.^...#",
        "#...*....v.....^...^...#",
        "#........v.....^...^.*.#",
        "######D#################",
        "#......................#",
        "#..a........B......a...#",
        "#......................#",
        "#.................E....#",
        "########################",
      ],
    },
    {
      id: "smelter", zone: "Foundry", name: "Smelter", time: 50,
      hint: "The furnace makes you grow without end, and a stud can't sink the floor gate while your endless tail still lies across the fence above. Find the cutter first.",
      grid: [
        "########################",
        "#S...I...a.............#",
        "###################v####",
        "#......................#",
        "#..a...................#",
        "#......................#",
        "#...*..............a...#",
        "#.....................x#",
        "#########^^^^###########",
        "#......................#",
        "#....a..........E......#",
        "#......................#",
        "########################",
      ],
    },
    {
      id: "forge-heart", zone: "Foundry", name: "Forge Heart", time: 60,
      bossHp: 4, bossLen: 14, bossAttackMs: 5500, flowers: 5,
      unproven: "a boss fight: the damage fruit and spike flowers appear at random",
      hint: "The one-eyed Serpent King slides through walls toward you. Only golden damage fruit hurts it, and one grows at a time. Dodge its worms and the red-ringed flowers; the exit opens when it falls.",
      grid: [
        "############################",
        "#S...........E.............#",
        "#.......................h..#",
        "#...##.....#####.....##....#",
        "#...##.....#...#.....##....#",
        "#..........#.a.#...........#",
        "#.a....................a...#",
        "#.......##....x....##......#",
        "#.......##.........##......#",
        "#..a...................a...#",
        "#...##.............##......#",
        "#...##.......@.....##......#",
        "#..........................#",
        "#.h..........+...........h.#",
        "############################",
      ],
    },
    {
      id: "night-stalker", zone: "Astral", name: "Night Stalker", time: 60,
      hint: "The black ghost is slow, but walls mean nothing to it. Keep moving.",
      grid: [
        "########################",
        "#S.....a..............E#",
        "#..###...##...###..##..#",
        "#..###...##...###..##..#",
        "#........##.a......##..#",
        "#........##......a.##..#",
        "#..####................#",
        "#..####......####.....a#",
        "#............####......#",
        "#.......###.......###..#",
        "#.a.....###.......###..#",
        "#g.........a.........X.#",
        "########################",
      ],
    },
    {
      id: "prism", zone: "Astral", name: "Prism", time: 50,
      hint: "The Rainbow is the smartest hunter: fast, and it takes the portals too. It never crashes — but box it in and it crumbles.",
      grid: [
        "########################",
        "#........a..E..........#",
        "#.1..................2.#",
        "#....##..........##....#",
        "#....##..........##....#",
        "#.........####.........#",
        "#S.a........U.......a..#",
        "#.........####.........#",
        "#....##..........##....#",
        "#....##..........##....#",
        "#.2.........a........1.#",
        "#...........+..a.......#",
        "########################",
      ],
    },
    {
      id: "dreamwalk", zone: "Astral", name: "Dreamwalk", time: 45,
      hint: "Dream blocks fling you straight through as a skeleton: no steering, and you pass through yourself. Hit a wall inside one and you bounce back — a U-turn where there's no room for one.",
      grid: [
        "########################",
        "############%###########",
        "############%###########",
        "############%###########",
        "############a###########",
        "##########.....#########",
        "#.....####.....###.....#",
        "#..a..####.....###..a..#",
        "#.S...%%%%.....###.....#",
        "#.....####.....%%%.....#",
        "#.....####...a.###.....#",
        "##########.....###...E.#",
        "##################.....#",
        "########################",
      ],
    },
    {
      id: "thunderhead", zone: "Astral", name: "Thunderhead", time: 30,
      hint: "In the storm you fly toward your pointer (your finger on a phone; arrow keys without one). It's fast — and the pillars are still walls.",
      grid: [
        "########################",
        "#......................#",
        "#...&&&&&&a&&&&&&&&&...#",
        "#...&&&&&&&&#&&&&&&&...#",
        "#...&&&##&&&#&&&&&a&...#",
        "#...&&&##&&&#&&&&&&&...#",
        "#S..&&&&&&&&#&&&&&&&..E#",
        "#...&&a&&&&&&&&##&&&...#",
        "#...&&&&##&a&&&##&&&...#",
        "#...&&&&##&&&&a&&&&&...#",
        "#...&&&&&&&&&&&&&&&&...#",
        "#......................#",
        "########################",
      ],
    },
    {
      id: "dream-relay", zone: "Astral", name: "Dream Relay", time: 45,
      hint: "Dream lanes carry you through gaps in the walls as a skeleton, bouncing off whatever stops them. The teleport pad only sends one way.",
      grid: [
        "########################",
        "#S.....#..............E#",
        "#......#.%%%%%%%%%%....#",
        "#..a...#.#.......a#....#",
        "#......%%%........#....#",
        "#......#.#........%%%%.#",
        "########.#..a.....#..a.#",
        "#......#.##########....#",
        "#..5...#..........#....#",
        "#......%%%%%%%%%%%%....#",
        "#.a....#.......5..#..a.#",
        "#......#..........#....#",
        "########################",
      ],
    },
    {
      id: "eye-of-the-storm", zone: "Astral", name: "Eye of the Storm", time: 45,
      hint: "Fly the storm into its calm, dark eye, and out again. The black ghost comes for you through all of it.",
      grid: [
        "########################",
        "#S.....................#",
        "#..&&&&&&&&&&&&&&&&&&..#",
        "#..&&&&&&&&&&&&&&&&&&..#",
        "#..&&&&::::::::::&&&&..#",
        "#..&&&&:...a....:&&&&..#",
        "#..&&&&:.a...E..:&&&&..#",
        "#..&&&&:....a...:&&&&..#",
        "#..&&&&::::::::::&&&&..#",
        "#..&&&&&&&&&&&&&&&&&&..#",
        "#..&&&&&&&&&&&&&&&&&&.X#",
        "#.a..................a.#",
        "########################",
      ],
    },
    {
      id: "starfall", zone: "Astral", name: "Starfall", time: 60,
      hint: "An apple floats in a dream pool; ghost through the rim or dive in and bounce out. The Rainbow is clever: box it in and it crumbles.",
      grid: [
        "########################",
        "#S.....#.....1.#.......#",
        "#......#.......#...a...#",
        "#..a...#..%%%..#.......#",
        "#......#..%a%..#...U...#",
        "#...g..#..%%%..#.......#",
        "#......####.####.......#",
        "#..........2...........#",
        "#####.##########.#######",
        "#......1.....a.....2...#",
        "#.a..................E.#",
        "#......................#",
        "########################",
      ],
    },
    {
      id: "serpent-king", zone: "Astral", name: "Serpent King", time: 90,
      bossHp: 5, bossAttackMs: 4000, flowers: 8, enemyMs: { boss: 230, worm: 105 },
      unproven: "a boss fight: the damage fruit and spike flowers appear at random",
      hint: "The Serpent King returns, longer and faster, and its spike flowers bloom eight at a time. Five damage fruit bring it down. The dream lanes are your fastest way across.",
      grid: [
        "############################",
        "#S.........................#",
        "#.h......a........a......h.#",
        "#...%%%%%%.......%%%%%%....#",
        "#..........###.............#",
        "#...##.....#E#.......##....#",
        "#...##.....#.#...a...##....#",
        "#.a.......t................#",
        "#...##...............##..a.#",
        "#...##........@......##....#",
        "#..............###.........#",
        "#...%%%%%%.......%%%%%%....#",
        "#.h......a........g......h.#",
        "#............$.............#",
        "############################",
      ],
    },
  ];
});
