/* =====================================================================
   Lanterns — dictionary builder (run with node, not shipped to the page).

     node build-data.js path/to/complete.json

   Sources
   - HSK 3.0 vocabulary with numeric pinyin, levels, frequency and
     glosses from drkameleon/complete-hsk-vocabulary (github), which
     compiles the official HSK lists with CC-CEDICT readings.
   - curated.js: this game's original hand-checked entries; they win
     over the dataset wherever both know a word.

   Keeps bands 1-6, pure-CJK words of 1-4 characters whose pinyin
   splits one syllable per character (so the tone-mark renderer is
   always right). Tiers: bands 1-2 -> 1, 3-4 -> 2, 5-6 -> 3.
   ===================================================================== */
"use strict";
const fs = require("fs");
const path = require("path");

const srcPath = process.argv[2] || "complete.json";
const raw = JSON.parse(fs.readFileSync(srcPath, "utf8"));

// ---- the curated overrides -------------------------------------------------
const sandbox = { window: {} };
new Function("window", fs.readFileSync(path.join(__dirname, "curated.js"), "utf8"))(sandbox.window);
const curated = new Map();
for (const [hz, pin, gloss, tier] of sandbox.window.LanternWords) curated.set(hz, [hz, pin, gloss, tier]);

// ---- helpers ----------------------------------------------------------------
const isCJK = (s) => [...s].every((ch) => /[\u4e00-\u9fff]/.test(ch));
function minBand(levels) {
  let m = Infinity;
  for (const l of levels || []) {
    const mm = /^(?:new|old|newest)-(\d+)/.exec(l);
    if (mm) m = Math.min(m, +mm[1]);
  }
  return m;
}
function normNumeric(num) {
  let s = num.toLowerCase().replace(/u:/g, "v").replace(/\u00fc/g, "v").trim();
  const toks = s.split(/\s+/).map((t) => {
    if (/^[a-z]+[1-5]$/.test(t)) return t;
    if (/^[a-z]+$/.test(t)) return t + "5";           // bare neutral
    return null;
  });
  return toks.every(Boolean) ? toks : null;
}
function pickGloss(meanings) {
  for (let m of meanings || []) {
    m = m.trim();
    if (/^(surname|old variant|variant of|used in)/i.test(m)) continue;
    m = m.replace(/\s*\(CL:[^)]*\)/g, "").replace(/\s+/g, " ").trim();
    if (!m) continue;
    if (m.length > 52) m = m.slice(0, 49).replace(/[,;/ ]+\S*$/, "") + "…";
    return m;
  }
  return null;
}

// ---- build -------------------------------------------------------------------
const out = new Map();
let dropped = { band: 0, cjk: 0, len: 0, pinyin: 0, syll: 0, gloss: 0 };
for (const e of raw) {
  const hz = e.simplified;
  const band = minBand(e.level);
  if (!(band >= 1 && band <= 6)) { dropped.band++; continue; }
  if (!isCJK(hz)) { dropped.cjk++; continue; }
  if (hz.length < 1 || hz.length > 4) { dropped.len++; continue; }
  // prefer a lowercase (common-noun) reading, else the first one
  const forms = e.forms || [];
  let form = forms.find((f) => f.transcriptions && /^[a-z]/.test(f.transcriptions.numeric || "")) || forms[0];
  if (!form || !form.transcriptions || !form.transcriptions.numeric) { dropped.pinyin++; continue; }
  const toks = normNumeric(form.transcriptions.numeric);
  if (!toks) { dropped.pinyin++; continue; }
  if (toks.length !== hz.length) { dropped.syll++; continue; }
  const gloss = pickGloss(form.meanings);
  if (!gloss) { dropped.gloss++; continue; }
  const tier = band <= 2 ? 1 : band <= 4 ? 2 : 3;
  const trad = (form.traditional && form.traditional !== hz &&
    form.traditional.length === hz.length) ? form.traditional : null;
  const row = trad ? [hz, toks.join(" "), gloss, tier, trad] : [hz, toks.join(" "), gloss, tier];
  if (!out.has(hz)) out.set(hz, { row, freq: e.frequency || 99999 });
}
// curated entries win on pinyin/gloss/tier, and pick up the dataset's
// traditional form; curated-only words fall back to their simplified.
for (const [hz, row] of curated) {
  const prev = out.get(hz);
  const trad = prev && prev.row[4] ? prev.row[4] : null;
  out.set(hz, { row: trad ? row.concat([trad]) : row, freq: (prev || {}).freq || 0 });
}

const rows = [...out.values()]
  .sort((a, b) => a.row[3] - b.row[3] || a.freq - b.freq)
  .map((o) => o.row);

// ---- emit ---------------------------------------------------------------------
const esc = (s) => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
let js = `/* =====================================================================
   Lanterns — the vocabulary. GENERATED by build-data.js; edit curated.js
   for hand-tuned entries and re-run the builder rather than editing here.

   [simplified, pinyin, gloss, tier, traditional?] (5th only if distinct)
   Tiers: HSK bands 1-2 -> 1, 3-4 -> 2, 5-6 -> 3 (${rows.length} words).
   Word data compiled from the HSK 3.0 lists with CC-CEDICT readings via
   github.com/drkameleon/complete-hsk-vocabulary (thank you!).
   ===================================================================== */
window.LanternWords = [
`;
js += rows.map((r) => `  ["${esc(r[0])}", "${esc(r[1])}", "${esc(r[2])}", ${r[3]}${r[4] ? `, "${esc(r[4])}"` : ""}]`).join(",\n");
js += "\n];\n";
fs.writeFileSync(path.join(__dirname, "data.js"), js);

const tiers = { 1: 0, 2: 0, 3: 0 };
rows.forEach((r) => tiers[r[3]]++);
console.log("words:", rows.length, "tiers:", tiers, "dropped:", dropped);
