/* =====================================================================
   Lanterns — the vocabulary. [hanzi, pinyin (tone numbers, 5 = neutral),
   gloss, tier]. Tier 1 = single characters, 2 = everyday words, 3 =
   longer phrases; the festival ramps 1 → 3. Typing uses the toneless
   form (spaces and numbers stripped, ü typed as v — u also accepted);
   Tone Master keeps the numbers.
   ===================================================================== */
window.LanternWords = [
  // ---- tier 1: single characters --------------------------------------
  ["我", "wo3", "I, me", 1],
  ["你", "ni3", "you", 1],
  ["他", "ta1", "he", 1],
  ["她", "ta1", "she", 1],
  ["好", "hao3", "good", 1],
  ["大", "da4", "big", 1],
  ["小", "xiao3", "small", 1],
  ["人", "ren2", "person", 1],
  ["山", "shan1", "mountain", 1],
  ["水", "shui3", "water", 1],
  ["火", "huo3", "fire", 1],
  ["天", "tian1", "sky, day", 1],
  ["上", "shang4", "up, above", 1],
  ["下", "xia4", "down, below", 1],
  ["中", "zhong1", "middle", 1],
  ["国", "guo2", "country", 1],
  ["家", "jia1", "home, family", 1],
  ["爱", "ai4", "to love", 1],
  ["猫", "mao1", "cat", 1],
  ["狗", "gou3", "dog", 1],
  ["鱼", "yu2", "fish", 1],
  ["马", "ma3", "horse", 1],
  ["鸟", "niao3", "bird", 1],
  ["茶", "cha2", "tea", 1],
  ["米", "mi3", "rice (grain)", 1],
  ["手", "shou3", "hand", 1],
  ["口", "kou3", "mouth", 1],
  ["心", "xin1", "heart", 1],
  ["门", "men2", "door", 1],
  ["月", "yue4", "moon, month", 1],
  ["日", "ri4", "sun, day", 1],
  ["年", "nian2", "year", 1],
  ["风", "feng1", "wind", 1],
  ["雨", "yu3", "rain", 1],
  ["雪", "xue3", "snow", 1],
  ["花", "hua1", "flower", 1],
  ["树", "shu4", "tree", 1],
  ["书", "shu1", "book", 1],
  ["车", "che1", "car, vehicle", 1],
  ["路", "lu4", "road", 1],
  ["东", "dong1", "east", 1],
  ["南", "nan2", "south", 1],
  ["西", "xi1", "west", 1],
  ["北", "bei3", "north", 1],
  ["白", "bai2", "white", 1],
  ["黑", "hei1", "black", 1],
  ["红", "hong2", "red", 1],
  ["高", "gao1", "tall, high", 1],
  ["长", "chang2", "long", 1],
  ["飞", "fei1", "to fly", 1],
  ["走", "zou3", "to walk", 1],
  ["看", "kan4", "to look", 1],
  ["听", "ting1", "to listen", 1],
  ["说", "shuo1", "to speak", 1],
  ["读", "du2", "to read", 1],
  ["写", "xie3", "to write", 1],
  ["吃", "chi1", "to eat", 1],
  ["喝", "he1", "to drink", 1],
  ["买", "mai3", "to buy", 1],
  ["卖", "mai4", "to sell", 1],
  ["开", "kai1", "to open", 1],
  ["关", "guan1", "to close", 1],
  ["来", "lai2", "to come", 1],
  ["去", "qu4", "to go", 1],
  ["坐", "zuo4", "to sit", 1],
  ["站", "zhan4", "to stand", 1],
  ["笑", "xiao4", "to laugh", 1],
  ["哭", "ku1", "to cry", 1],
  ["钱", "qian2", "money", 1],
  ["菜", "cai4", "dish, vegetable", 1],
  ["肉", "rou4", "meat", 1],
  ["汤", "tang1", "soup", 1],
  ["光", "guang1", "light", 1],
  ["星", "xing1", "star", 1],
  ["云", "yun2", "cloud", 1],
  ["海", "hai3", "sea", 1],
  ["河", "he2", "river", 1],
  ["桥", "qiao2", "bridge", 1],
  ["灯", "deng1", "lamp", 1],
  ["龙", "long2", "dragon", 1],
  ["虎", "hu3", "tiger", 1],
  ["羊", "yang2", "sheep", 1],
  ["牛", "niu2", "cow", 1],
  ["鸡", "ji1", "chicken", 1],
  ["兔", "tu4", "rabbit", 1],
  ["蛇", "she2", "snake", 1],
  ["一", "yi1", "one", 1],
  ["二", "er4", "two", 1],
  ["三", "san1", "three", 1],
  ["四", "si4", "four", 1],
  ["五", "wu3", "five", 1],
  ["六", "liu4", "six", 1],
  ["七", "qi1", "seven", 1],
  ["八", "ba1", "eight", 1],
  ["九", "jiu3", "nine", 1],
  ["十", "shi2", "ten", 1],
  ["谁", "shei2", "who", 1],

  // ---- tier 2: everyday words ------------------------------------------
  ["你好", "ni3 hao3", "hello", 2],
  ["谢谢", "xie4 xie5", "thank you", 2],
  ["再见", "zai4 jian4", "goodbye", 2],
  ["中国", "zhong1 guo2", "China", 2],
  ["北京", "bei3 jing1", "Beijing", 2],
  ["上海", "shang4 hai3", "Shanghai", 2],
  ["朋友", "peng2 you5", "friend", 2],
  ["老师", "lao3 shi1", "teacher", 2],
  ["学生", "xue2 sheng5", "student", 2],
  ["学校", "xue2 xiao4", "school", 2],
  ["医生", "yi1 sheng1", "doctor", 2],
  ["妈妈", "ma1 ma5", "mom", 2],
  ["爸爸", "ba4 ba5", "dad", 2],
  ["哥哥", "ge1 ge5", "older brother", 2],
  ["姐姐", "jie3 jie5", "older sister", 2],
  ["弟弟", "di4 di5", "younger brother", 2],
  ["妹妹", "mei4 mei5", "younger sister", 2],
  ["今天", "jin1 tian1", "today", 2],
  ["明天", "ming2 tian1", "tomorrow", 2],
  ["昨天", "zuo2 tian1", "yesterday", 2],
  ["现在", "xian4 zai4", "now", 2],
  ["时间", "shi2 jian1", "time", 2],
  ["什么", "shen2 me5", "what", 2],
  ["怎么", "zen3 me5", "how", 2],
  ["名字", "ming2 zi5", "name", 2],
  ["电话", "dian4 hua4", "telephone", 2],
  ["电脑", "dian4 nao3", "computer", 2],
  ["电影", "dian4 ying3", "movie", 2],
  ["电视", "dian4 shi4", "television", 2],
  ["手机", "shou3 ji1", "mobile phone", 2],
  ["飞机", "fei1 ji1", "airplane", 2],
  ["火车", "huo3 che1", "train", 2],
  ["汽车", "qi4 che1", "car", 2],
  ["苹果", "ping2 guo3", "apple", 2],
  ["西瓜", "xi1 gua1", "watermelon", 2],
  ["米饭", "mi3 fan4", "cooked rice", 2],
  ["面条", "mian4 tiao2", "noodles", 2],
  ["牛奶", "niu2 nai3", "milk", 2],
  ["咖啡", "ka1 fei1", "coffee", 2],
  ["啤酒", "pi2 jiu3", "beer", 2],
  ["商店", "shang1 dian4", "shop", 2],
  ["饭馆", "fan4 guan3", "restaurant", 2],
  ["公园", "gong1 yuan2", "park", 2],
  ["机场", "ji1 chang3", "airport", 2],
  ["房间", "fang2 jian1", "room", 2],
  ["桌子", "zhuo1 zi5", "table", 2],
  ["椅子", "yi3 zi5", "chair", 2],
  ["杯子", "bei1 zi5", "cup", 2],
  ["孩子", "hai2 zi5", "child", 2],
  ["儿子", "er2 zi5", "son", 2],
  ["女儿", "nv3 er2", "daughter", 2],
  ["先生", "xian1 sheng5", "Mr., sir", 2],
  ["漂亮", "piao4 liang5", "pretty", 2],
  ["高兴", "gao1 xing4", "happy", 2],
  ["喜欢", "xi3 huan1", "to like", 2],
  ["认识", "ren4 shi5", "to know (someone)", 2],
  ["知道", "zhi1 dao4", "to know", 2],
  ["觉得", "jue2 de5", "to feel, think", 2],
  ["希望", "xi1 wang4", "to hope", 2],
  ["帮助", "bang1 zhu4", "to help", 2],
  ["学习", "xue2 xi2", "to study", 2],
  ["工作", "gong1 zuo4", "work, job", 2],
  ["睡觉", "shui4 jiao4", "to sleep", 2],
  ["起床", "qi3 chuang2", "to get up", 2],
  ["吃饭", "chi1 fan4", "to eat a meal", 2],
  ["说话", "shuo1 hua4", "to talk", 2],
  ["唱歌", "chang4 ge1", "to sing", 2],
  ["跳舞", "tiao4 wu3", "to dance", 2],
  ["游泳", "you2 yong3", "to swim", 2],
  ["跑步", "pao3 bu4", "to run", 2],
  ["看书", "kan4 shu1", "to read books", 2],
  ["旅游", "lv3 you2", "to travel", 2],
  ["天气", "tian1 qi4", "weather", 2],
  ["下雨", "xia4 yu3", "to rain", 2],
  ["下雪", "xia4 xue3", "to snow", 2],
  ["太阳", "tai4 yang2", "sun", 2],
  ["月亮", "yue4 liang5", "moon", 2],
  ["星星", "xing1 xing5", "stars", 2],
  ["灯笼", "deng1 long2", "lantern", 2],
  ["愿望", "yuan4 wang4", "wish", 2],
  ["新年", "xin1 nian2", "new year", 2],
  ["快乐", "kuai4 le4", "happy, joyful", 2],
  ["生日", "sheng1 ri4", "birthday", 2],
  ["礼物", "li3 wu4", "gift", 2],
  ["红色", "hong2 se4", "red (color)", 2],
  ["颜色", "yan2 se4", "color", 2],
  ["东西", "dong1 xi5", "thing", 2],
  ["左边", "zuo3 bian1", "left side", 2],
  ["右边", "you4 bian1", "right side", 2],
  ["前面", "qian2 mian4", "in front", 2],
  ["后面", "hou4 mian4", "behind", 2],
  ["里面", "li3 mian4", "inside", 2],
  ["外面", "wai4 mian4", "outside", 2],
  ["多少", "duo1 shao3", "how many", 2],
  ["一起", "yi1 qi3", "together", 2],
  ["已经", "yi3 jing1", "already", 2],
  ["还是", "hai2 shi4", "or, still", 2],
  ["但是", "dan4 shi4", "but", 2],
  ["因为", "yin1 wei4", "because", 2],
  ["所以", "suo3 yi3", "therefore", 2],
  ["可以", "ke3 yi3", "can, may", 2],
  ["可能", "ke3 neng2", "maybe", 2],
  ["应该", "ying1 gai1", "should", 2],
  ["非常", "fei1 chang2", "very", 2],
  ["每天", "mei3 tian1", "every day", 2],
  ["大家", "da4 jia1", "everyone", 2],
  ["小心", "xiao3 xin1", "careful", 2],
  ["开心", "kai1 xin1", "happy", 2],
  ["放心", "fang4 xin1", "to relax, rest assured", 2],
  ["加油", "jia1 you2", "go for it!", 2],
  ["时候", "shi2 hou5", "time, moment", 2],
  ["地方", "di4 fang5", "place", 2],
  ["身体", "shen1 ti3", "body, health", 2],
  ["眼睛", "yan3 jing1", "eyes", 2],
  ["耳朵", "er3 duo5", "ear", 2],
  ["中文", "zhong1 wen2", "Chinese (language)", 2],
  ["汉字", "han4 zi4", "Chinese character", 2],
  ["音乐", "yin1 yue4", "music", 2],
  ["运动", "yun4 dong4", "sports", 2],

  // ---- tier 3: longer phrases -------------------------------------------
  ["对不起", "dui4 bu5 qi3", "sorry", 3],
  ["没关系", "mei2 guan1 xi5", "it's okay", 3],
  ["不客气", "bu4 ke4 qi5", "you're welcome", 3],
  ["图书馆", "tu2 shu1 guan3", "library", 3],
  ["办公室", "ban4 gong1 shi4", "office", 3],
  ["服务员", "fu2 wu4 yuan2", "waiter", 3],
  ["出租车", "chu1 zu1 che1", "taxi", 3],
  ["自行车", "zi4 xing2 che1", "bicycle", 3],
  ["火车站", "huo3 che1 zhan4", "train station", 3],
  ["为什么", "wei4 shen2 me5", "why", 3],
  ["星期天", "xing1 qi1 tian1", "Sunday", 3],
  ["普通话", "pu3 tong1 hua4", "Mandarin", 3],
  ["动物园", "dong4 wu4 yuan2", "zoo", 3],
  ["咖啡馆", "ka1 fei1 guan3", "café", 3],
  ["生日快乐", "sheng1 ri4 kuai4 le4", "happy birthday", 3],
  ["新年快乐", "xin1 nian2 kuai4 le4", "happy new year", 3],

  // ---- expansion: more single characters --------------------------------
  ["早", "zao3", "early, morning", 1], ["晚", "wan3", "late, evening", 1],
  ["冷", "leng3", "cold", 1], ["热", "re4", "hot", 1],
  ["新", "xin1", "new", 1], ["旧", "jiu4", "old (things)", 1],
  ["多", "duo1", "many", 1], ["少", "shao3", "few", 1],
  ["快", "kuai4", "fast", 1], ["慢", "man4", "slow", 1],
  ["远", "yuan3", "far", 1], ["近", "jin4", "near", 1],
  ["前", "qian2", "front", 1], ["后", "hou4", "back", 1],
  ["男", "nan2", "male", 1], ["女", "nv3", "female", 1],
  ["头", "tou2", "head", 1], ["脸", "lian3", "face", 1],
  ["脚", "jiao3", "foot", 1], ["腿", "tui3", "leg", 1],
  ["药", "yao4", "medicine", 1], ["病", "bing4", "illness", 1],
  ["累", "lei4", "tired", 1], ["忙", "mang2", "busy", 1],
  ["贵", "gui4", "expensive", 1], ["难", "nan2", "difficult", 1],
  ["字", "zi4", "character", 1], ["话", "hua4", "speech", 1],
  ["事", "shi4", "matter", 1], ["岁", "sui4", "years old", 1],
  ["元", "yuan2", "yuan", 1], ["号", "hao4", "number, date", 1],
  ["街", "jie1", "street", 1], ["城", "cheng2", "town", 1],
  ["店", "dian4", "shop", 1], ["床", "chuang2", "bed", 1],
  ["窗", "chuang1", "window", 1], ["纸", "zhi3", "paper", 1],
  ["笔", "bi3", "pen", 1], ["刀", "dao1", "knife", 1],
  ["碗", "wan3", "bowl", 1], ["糖", "tang2", "sugar, candy", 1],
  ["盐", "yan2", "salt", 1], ["油", "you2", "oil", 1],
  ["冰", "bing1", "ice", 1], ["梦", "meng4", "dream", 1],
  ["歌", "ge1", "song", 1], ["舞", "wu3", "dance", 1],
  ["球", "qiu2", "ball", 1], ["票", "piao4", "ticket", 1],
  ["信", "xin4", "letter", 1], ["船", "chuan2", "boat", 1],
  ["春", "chun1", "spring", 1], ["夏", "xia4", "summer", 1],
  ["秋", "qiu1", "autumn", 1], ["冬", "dong1", "winter", 1],
  ["金", "jin1", "gold", 1], ["银", "yin2", "silver", 1],
  ["铁", "tie3", "iron", 1], ["石", "shi2", "stone", 1],
  ["土", "tu3", "earth", 1], ["木", "mu4", "wood", 1],
  ["林", "lin2", "forest", 1], ["田", "tian2", "field", 1],
  ["草", "cao3", "grass", 1], ["叶", "ye4", "leaf", 1],
  ["果", "guo3", "fruit", 1], ["瓜", "gua1", "melon", 1],
  ["豆", "dou4", "bean", 1], ["虫", "chong2", "insect", 1],
  ["熊", "xiong2", "bear", 1], ["象", "xiang4", "elephant", 1],
  ["鹿", "lu4", "deer", 1], ["猴", "hou2", "monkey", 1],
  ["鼠", "shu3", "mouse", 1], ["猪", "zhu1", "pig", 1],
  ["楼", "lou2", "building", 1], ["画", "hua4", "to draw", 1],
  ["洗", "xi3", "to wash", 1], ["唱", "chang4", "to sing", 1],
  ["跳", "tiao4", "to jump", 1], ["跑", "pao3", "to run", 1],
  ["睡", "shui4", "to sleep", 1], ["穿", "chuan1", "to wear", 1],
  ["玩", "wan2", "to play", 1], ["等", "deng3", "to wait", 1],
  ["找", "zhao3", "to look for", 1], ["送", "song4", "to send, give", 1],
  ["用", "yong4", "to use", 1], ["做", "zuo4", "to do", 1],
  ["想", "xiang3", "to think, want", 1], ["要", "yao4", "to want", 1],
  ["能", "neng2", "can", 1], ["会", "hui4", "can, will", 1],
  ["学", "xue2", "to learn", 1], ["教", "jiao1", "to teach", 1],
  ["问", "wen4", "to ask", 1], ["帮", "bang1", "to help", 1],
  ["给", "gei3", "to give", 1],

  // ---- expansion: everyday words -----------------------------------------
  ["早上", "zao3 shang5", "morning", 2], ["晚上", "wan3 shang5", "evening", 2],
  ["中午", "zhong1 wu3", "noon", 2], ["上午", "shang4 wu3", "morning (a.m.)", 2],
  ["下午", "xia4 wu3", "afternoon", 2], ["早饭", "zao3 fan4", "breakfast", 2],
  ["午饭", "wu3 fan4", "lunch", 2], ["晚饭", "wan3 fan4", "dinner", 2],
  ["去年", "qu4 nian2", "last year", 2], ["今年", "jin1 nian2", "this year", 2],
  ["明年", "ming2 nian2", "next year", 2], ["小时", "xiao3 shi2", "hour", 2],
  ["分钟", "fen1 zhong1", "minute", 2], ["星期", "xing1 qi1", "week", 2],
  ["周末", "zhou1 mo4", "weekend", 2], ["生气", "sheng1 qi4", "angry", 2],
  ["舒服", "shu1 fu5", "comfortable", 2], ["好吃", "hao3 chi1", "delicious", 2],
  ["好看", "hao3 kan4", "good-looking", 2], ["好玩", "hao3 wan2", "fun", 2],
  ["有名", "you3 ming2", "famous", 2], ["干净", "gan1 jing4", "clean", 2],
  ["安静", "an1 jing4", "quiet", 2], ["热闹", "re4 nao5", "lively", 2],
  ["方便", "fang1 bian4", "convenient", 2], ["便宜", "pian2 yi5", "cheap", 2],
  ["容易", "rong2 yi4", "easy", 2], ["问题", "wen4 ti2", "question", 2],
  ["意思", "yi4 si5", "meaning", 2], ["事情", "shi4 qing5", "matter", 2],
  ["衣服", "yi1 fu5", "clothes", 2], ["裤子", "ku4 zi5", "pants", 2],
  ["裙子", "qun2 zi5", "skirt", 2], ["鞋子", "xie2 zi5", "shoes", 2],
  ["帽子", "mao4 zi5", "hat", 2], ["袜子", "wa4 zi5", "socks", 2],
  ["手表", "shou3 biao3", "wristwatch", 2], ["眼镜", "yan3 jing4", "glasses", 2],
  ["铅笔", "qian1 bi3", "pencil", 2], ["报纸", "bao4 zhi3", "newspaper", 2],
  ["地图", "di4 tu2", "map", 2], ["照片", "zhao4 pian4", "photo", 2],
  ["电梯", "dian4 ti1", "elevator", 2], ["冰箱", "bing1 xiang1", "fridge", 2],
  ["空调", "kong1 tiao2", "air conditioner", 2], ["医院", "yi1 yuan4", "hospital", 2],
  ["银行", "yin2 hang2", "bank", 2], ["超市", "chao1 shi4", "supermarket", 2],
  ["邮局", "you2 ju2", "post office", 2], ["教室", "jiao4 shi4", "classroom", 2],
  ["厨房", "chu2 fang2", "kitchen", 2], ["厕所", "ce4 suo3", "toilet", 2],
  ["城市", "cheng2 shi4", "city", 2], ["农村", "nong2 cun1", "countryside", 2],
  ["地铁", "di4 tie3", "subway", 2], ["走路", "zou3 lu4", "to walk", 2],
  ["开车", "kai1 che1", "to drive", 2], ["骑车", "qi2 che1", "to ride a bike", 2],
  ["迟到", "chi2 dao4", "to be late", 2], ["离开", "li2 kai1", "to leave", 2],
  ["回家", "hui2 jia1", "to go home", 2], ["回来", "hui2 lai2", "to come back", 2],
  ["出去", "chu1 qu4", "to go out", 2], ["进来", "jin4 lai2", "to come in", 2],
  ["休息", "xiu1 xi5", "to rest", 2], ["锻炼", "duan4 lian4", "to exercise", 2],
  ["爬山", "pa2 shan1", "to hike", 2], ["钓鱼", "diao4 yu2", "to fish", 2],
  ["做饭", "zuo4 fan4", "to cook", 2], ["洗澡", "xi3 zao3", "to shower", 2],
  ["刷牙", "shua1 ya2", "to brush teeth", 2], ["起来", "qi3 lai2", "to get up", 2],
  ["打开", "da3 kai1", "to open", 2], ["关门", "guan1 men2", "to close the door", 2],
  ["上班", "shang4 ban1", "to go to work", 2], ["下班", "xia4 ban1", "to get off work", 2],
  ["上课", "shang4 ke4", "to attend class", 2], ["下课", "xia4 ke4", "class is over", 2],
  ["考试", "kao3 shi4", "exam", 2], ["作业", "zuo4 ye4", "homework", 2],
  ["汉语", "han4 yu3", "Chinese language", 2], ["英语", "ying1 yu3", "English", 2],
  ["数学", "shu4 xue2", "math", 2], ["历史", "li4 shi3", "history", 2],
  ["故事", "gu4 shi5", "story", 2], ["新闻", "xin1 wen2", "news", 2],
  ["世界", "shi4 jie4", "world", 2], ["国家", "guo2 jia1", "country", 2],
  ["首都", "shou3 du1", "capital city", 2], ["长城", "chang2 cheng2", "the Great Wall", 2],
  ["熊猫", "xiong2 mao1", "panda", 2], ["老虎", "lao3 hu3", "tiger", 2],
  ["香蕉", "xiang1 jiao1", "banana", 2], ["鸡蛋", "ji1 dan4", "egg", 2],
  ["蛋糕", "dan4 gao1", "cake", 2], ["面包", "mian4 bao1", "bread", 2],
  ["包子", "bao1 zi5", "steamed bun", 2], ["饺子", "jiao3 zi5", "dumpling", 2],
  ["豆腐", "dou4 fu5", "tofu", 2], ["大学", "da4 xue2", "university", 2],
  ["中学", "zhong1 xue2", "middle school", 2], ["小学", "xiao3 xue2", "primary school", 2],
  ["春天", "chun1 tian1", "springtime", 2], ["夏天", "xia4 tian1", "summertime", 2],
  ["秋天", "qiu1 tian1", "autumn", 2], ["冬天", "dong1 tian1", "wintertime", 2],
  ["刮风", "gua1 feng1", "windy", 2], ["彩虹", "cai3 hong2", "rainbow", 2],
  ["烟花", "yan1 hua1", "fireworks", 2], ["节日", "jie2 ri4", "festival", 2],
  ["春节", "chun1 jie2", "Spring Festival", 2], ["中秋", "zhong1 qiu1", "Mid-Autumn", 2],
  ["月饼", "yue4 bing3", "mooncake", 2], ["红包", "hong2 bao1", "red envelope", 2],
  ["干杯", "gan1 bei1", "cheers!", 2], ["恭喜", "gong1 xi3", "congratulations", 2],
  ["结婚", "jie2 hun1", "to marry", 2], ["生活", "sheng1 huo2", "life", 2],
  ["司机", "si1 ji1", "driver", 2], ["警察", "jing3 cha2", "police", 2],
  ["护士", "hu4 shi5", "nurse", 2], ["演员", "yan3 yuan2", "actor", 2],
  ["歌手", "ge1 shou3", "singer", 2], ["画家", "hua4 jia1", "painter", 2],
  ["作家", "zuo4 jia1", "writer", 2], ["邻居", "lin2 ju1", "neighbor", 2],
  ["客人", "ke4 ren2", "guest", 2], ["阿姨", "a1 yi2", "aunt", 2],
  ["叔叔", "shu1 shu5", "uncle", 2], ["爷爷", "ye2 ye5", "grandpa", 2],
  ["奶奶", "nai3 nai5", "grandma", 2], ["或者", "huo4 zhe3", "or", 2],
  ["如果", "ru2 guo3", "if", 2], ["虽然", "sui1 ran2", "although", 2],
  ["然后", "ran2 hou4", "then", 2], ["开始", "kai1 shi3", "to begin", 2],
  ["结束", "jie2 shu4", "to end", 2], ["完成", "wan2 cheng2", "to complete", 2],
  ["准备", "zhun3 bei4", "to prepare", 2], ["决定", "jue2 ding4", "to decide", 2],
  ["需要", "xu1 yao4", "to need", 2], ["必须", "bi4 xu1", "must", 2],
  ["一定", "yi1 ding4", "definitely", 2], ["当然", "dang1 ran2", "of course", 2],
  ["马上", "ma3 shang4", "right away", 2], ["刚才", "gang1 cai2", "just now", 2],
  ["以前", "yi3 qian2", "before", 2], ["以后", "yi3 hou4", "afterwards", 2],
  ["最近", "zui4 jin4", "recently", 2], ["永远", "yong3 yuan3", "forever", 2],
  ["一样", "yi1 yang4", "the same", 2], ["不同", "bu4 tong2", "different", 2],
  ["重要", "zhong4 yao4", "important", 2], ["有趣", "you3 qu4", "interesting", 2],
  ["无聊", "wu2 liao2", "boring", 2], ["奇怪", "qi2 guai4", "strange", 2],
  ["聪明", "cong1 ming5", "smart", 2], ["努力", "nu3 li4", "hardworking", 2],
  ["认真", "ren4 zhen1", "serious", 2], ["热情", "re4 qing2", "enthusiastic", 2],
  ["友好", "you3 hao3", "friendly", 2], ["幸福", "xing4 fu2", "happiness", 2],
  ["健康", "jian4 kang1", "healthy", 2], ["安全", "an1 quan2", "safe", 2],
  ["危险", "wei1 xian3", "dangerous", 2],

  // ---- expansion: longer phrases -------------------------------------------
  ["打电话", "da3 dian4 hua4", "to make a call", 3],
  ["看电视", "kan4 dian4 shi4", "to watch TV", 3],
  ["玩游戏", "wan2 you2 xi4", "to play games", 3],
  ["踢足球", "ti1 zu2 qiu2", "to play soccer", 3],
  ["打篮球", "da3 lan2 qiu2", "to play basketball", 3],
  ["中国人", "zhong1 guo2 ren2", "Chinese person", 3],
  ["外国人", "wai4 guo2 ren2", "foreigner", 3],
  ["小笼包", "xiao3 long2 bao1", "soup dumpling", 3],
  ["巧克力", "qiao3 ke4 li4", "chocolate", 3],
  ["冰淇淋", "bing1 qi2 lin2", "ice cream", 3],
  ["圣诞节", "sheng4 dan4 jie2", "Christmas", 3],
  ["电影院", "dian4 ying3 yuan4", "cinema", 3],
  ["游泳池", "you2 yong3 chi2", "swimming pool", 3],
  ["洗手间", "xi3 shou3 jian1", "restroom", 3],
  ["没问题", "mei2 wen4 ti2", "no problem", 3],
  ["不好意思", "bu4 hao3 yi4 si5", "excuse me", 3],

  // ---- expansion II: taste, feel, describe --------------------------------
  ["甜", "tian2", "sweet", 1], ["酸", "suan1", "sour", 1],
  ["苦", "ku3", "bitter", 1], ["辣", "la4", "spicy", 1],
  ["咸", "xian2", "salty", 1], ["饿", "e4", "hungry", 1],
  ["渴", "ke3", "thirsty", 1], ["饱", "bao3", "full (eaten)", 1],
  ["对", "dui4", "correct", 1], ["错", "cuo4", "wrong", 1],
  ["真", "zhen1", "real", 1], ["假", "jia3", "fake", 1],
  ["满", "man3", "full", 1], ["空", "kong1", "empty", 1],
  ["干", "gan1", "dry", 1], ["湿", "shi1", "wet", 1],
  ["亮", "liang4", "bright", 1], ["暗", "an4", "dark", 1],
  ["轻", "qing1", "light (weight)", 1], ["重", "zhong4", "heavy", 1],
  ["胖", "pang4", "fat", 1], ["瘦", "shou4", "thin", 1],
  ["强", "qiang2", "strong", 1], ["弱", "ruo4", "weak", 1],
  ["深", "shen1", "deep", 1], ["浅", "qian3", "shallow", 1],
  ["宽", "kuan1", "wide", 1], ["窄", "zhai3", "narrow", 1],
  ["梨", "li2", "pear", 1], ["湖", "hu2", "lake", 1],
  ["岛", "dao3", "island", 1], ["墙", "qiang2", "wall", 1],

  // ---- expansion II: people ------------------------------------------------
  ["丈夫", "zhang4 fu5", "husband", 2], ["妻子", "qi1 zi5", "wife", 2],
  ["父亲", "fu4 qin1", "father", 2], ["母亲", "mu3 qin1", "mother", 2],
  ["同学", "tong2 xue2", "classmate", 2], ["同事", "tong2 shi4", "colleague", 2],
  ["老板", "lao3 ban3", "boss", 2], ["经理", "jing1 li3", "manager", 2],
  ["校长", "xiao4 zhang3", "principal", 2], ["别人", "bie2 ren2", "other people", 2],
  ["自己", "zi4 ji3", "oneself", 2],

  // ---- expansion II: body and health ---------------------------------------
  ["头发", "tou2 fa5", "hair", 2], ["鼻子", "bi2 zi5", "nose", 2],
  ["嘴巴", "zui3 ba1", "mouth", 2], ["肚子", "du4 zi5", "belly", 2],
  ["感冒", "gan3 mao4", "a cold", 2], ["发烧", "fa1 shao1", "fever", 2],
  ["咳嗽", "ke2 sou5", "to cough", 2], ["头疼", "tou2 teng2", "headache", 2],
  ["检查", "jian3 cha2", "to examine", 2], ["打针", "da3 zhen1", "injection", 2],
  ["吃药", "chi1 yao4", "to take medicine", 2],

  // ---- expansion II: food and drink -----------------------------------------
  ["味道", "wei4 dao4", "taste, flavor", 2], ["好喝", "hao3 he1", "tasty (drink)", 2],
  ["饮料", "yin3 liao4", "beverage", 2], ["果汁", "guo3 zhi1", "juice", 2],
  ["茶叶", "cha2 ye4", "tea leaves", 2], ["白酒", "bai2 jiu3", "baijiu", 2],
  ["红酒", "hong2 jiu3", "red wine", 2], ["火锅", "huo3 guo1", "hot pot", 2],
  ["烤鸭", "kao3 ya1", "roast duck", 2], ["羊肉", "yang2 rou4", "lamb", 2],
  ["牛肉", "niu2 rou4", "beef", 2], ["猪肉", "zhu1 rou4", "pork", 2],
  ["青菜", "qing1 cai4", "greens", 2], ["水果", "shui3 guo3", "fruit", 2],
  ["葡萄", "pu2 tao5", "grapes", 2], ["草莓", "cao3 mei2", "strawberry", 2],
  ["橙子", "cheng2 zi5", "orange", 2], ["桃子", "tao2 zi5", "peach", 2],

  // ---- expansion II: around the house ----------------------------------------
  ["房子", "fang2 zi5", "house", 2], ["客厅", "ke4 ting1", "living room", 2],
  ["卧室", "wo4 shi4", "bedroom", 2], ["阳台", "yang2 tai2", "balcony", 2],
  ["家具", "jia1 ju4", "furniture", 2], ["沙发", "sha1 fa1", "sofa", 2],
  ["钥匙", "yao4 shi5", "key", 2], ["钱包", "qian2 bao1", "wallet", 2],
  ["行李", "xing2 li5", "luggage", 2], ["箱子", "xiang1 zi5", "suitcase", 2],
  ["雨伞", "yu3 san3", "umbrella", 2], ["毛巾", "mao2 jin1", "towel", 2],
  ["牙刷", "ya2 shua1", "toothbrush", 2], ["肥皂", "fei2 zao4", "soap", 2],
  ["镜子", "jing4 zi5", "mirror", 2], ["垃圾", "la1 ji1", "trash", 2],
  ["打扫", "da3 sao3", "to clean", 2], ["收拾", "shou1 shi5", "to tidy up", 2],
  ["窗户", "chuang1 hu5", "window", 2], ["地板", "di4 ban3", "floor", 2],

  // ---- expansion II: time and tech -------------------------------------------
  ["过去", "guo4 qu4", "the past", 2], ["未来", "wei4 lai2", "the future", 2],
  ["世纪", "shi4 ji4", "century", 2], ["季节", "ji4 jie2", "season", 2],
  ["假期", "jia4 qi1", "vacation", 2], ["暑假", "shu3 jia4", "summer break", 2],
  ["寒假", "han2 jia4", "winter break", 2], ["年级", "nian2 ji2", "grade (school)", 2],
  ["号码", "hao4 ma3", "number", 2], ["短信", "duan3 xin4", "text message", 2],
  ["网站", "wang3 zhan4", "website", 2], ["网络", "wang3 luo4", "internet", 2],
  ["上网", "shang4 wang3", "to go online", 2], ["密码", "mi4 ma3", "password", 2],
  ["游戏", "you2 xi4", "game", 2], ["节目", "jie2 mu4", "TV program", 2],
  ["比赛", "bi3 sai4", "match, contest", 2], ["冠军", "guan4 jun1", "champion", 2],
  ["教练", "jiao4 lian4", "coach", 2], ["足球", "zu2 qiu2", "soccer", 2],
  ["篮球", "lan2 qiu2", "basketball", 2], ["网球", "wang3 qiu2", "tennis", 2],

  // ---- expansion II: study and work --------------------------------------------
  ["课本", "ke4 ben3", "textbook", 2], ["词典", "ci2 dian3", "dictionary", 2],
  ["句子", "ju4 zi5", "sentence", 2], ["单词", "dan1 ci2", "vocabulary word", 2],
  ["语法", "yu3 fa3", "grammar", 2], ["发音", "fa1 yin1", "pronunciation", 2],
  ["水平", "shui3 ping2", "level", 2], ["成绩", "cheng2 ji4", "grades, results", 2],
  ["毕业", "bi4 ye4", "to graduate", 2], ["复习", "fu4 xi2", "to review", 2],
  ["预习", "yu4 xi2", "to preview", 2], ["练习", "lian4 xi2", "to practice", 2],
  ["翻译", "fan1 yi4", "to translate", 2], ["解释", "jie3 shi4", "to explain", 2],
  ["回答", "hui2 da2", "to answer", 2], ["讨论", "tao3 lun4", "to discuss", 2],
  ["会议", "hui4 yi4", "meeting", 2], ["报告", "bao4 gao4", "report", 2],
  ["计划", "ji4 hua4", "plan", 2], ["目标", "mu4 biao1", "goal", 2],
  ["机会", "ji1 hui4", "opportunity", 2], ["经验", "jing1 yan4", "experience", 2],
  ["能力", "neng2 li4", "ability", 2], ["工资", "gong1 zi1", "salary", 2],
  ["加班", "jia1 ban1", "to work overtime", 2], ["出差", "chu1 chai1", "business trip", 2],
  ["面试", "mian4 shi4", "job interview", 2], ["简历", "jian3 li4", "resume", 2],

  // ---- expansion II: feelings ----------------------------------------------------
  ["心情", "xin1 qing2", "mood", 2], ["感觉", "gan3 jue2", "feeling", 2],
  ["感情", "gan3 qing2", "emotion, affection", 2], ["兴趣", "xing4 qu4", "interest", 2],
  ["爱好", "ai4 hao4", "hobby", 2], ["习惯", "xi2 guan4", "habit", 2],
  ["态度", "tai4 du4", "attitude", 2], ["性格", "xing4 ge2", "personality", 2],
  ["脾气", "pi2 qi5", "temper", 2], ["记得", "ji4 de5", "to remember", 2],
  ["忘记", "wang4 ji4", "to forget", 2], ["担心", "dan1 xin1", "to worry", 2],
  ["害怕", "hai4 pa4", "to fear", 2], ["紧张", "jin3 zhang1", "nervous", 2],
  ["兴奋", "xing1 fen4", "excited", 2], ["骄傲", "jiao1 ao4", "proud", 2],
  ["后悔", "hou4 hui3", "to regret", 2], ["羡慕", "xian4 mu4", "to envy", 2],
  ["讨厌", "tao3 yan4", "to dislike", 2], ["满意", "man3 yi4", "satisfied", 2],
  ["失望", "shi1 wang4", "disappointed", 2], ["孤单", "gu1 dan1", "lonely", 2],

  // ---- expansion II: the wider world ----------------------------------------------
  ["文化", "wen2 hua4", "culture", 2], ["传统", "chuan2 tong3", "tradition", 2],
  ["艺术", "yi4 shu4", "art", 2], ["科学", "ke1 xue2", "science", 2],
  ["技术", "ji4 shu4", "technology", 2], ["经济", "jing1 ji4", "economy", 2],
  ["政府", "zheng4 fu3", "government", 2], ["社会", "she4 hui4", "society", 2],
  ["环境", "huan2 jing4", "environment", 2], ["污染", "wu1 ran3", "pollution", 2],
  ["保护", "bao3 hu4", "to protect", 2], ["自然", "zi4 ran2", "nature", 2],
  ["动物", "dong4 wu4", "animal", 2], ["植物", "zhi2 wu4", "plant", 2],
  ["地球", "di4 qiu2", "the Earth", 2], ["宇宙", "yu3 zhou4", "universe", 2],
  ["广告", "guang3 gao4", "advertisement", 2], ["顾客", "gu4 ke4", "customer", 2],
  ["价格", "jia4 ge2", "price", 2], ["质量", "zhi4 liang4", "quality", 2],
  ["服务", "fu2 wu4", "service", 2], ["免费", "mian3 fei4", "free of charge", 2],
  ["打折", "da3 zhe2", "discount", 2], ["商量", "shang1 liang5", "to discuss, consult", 2],
  ["联系", "lian2 xi4", "to contact", 2], ["交流", "jiao1 liu2", "to communicate", 2],
  ["介绍", "jie4 shao4", "to introduce", 2], ["参加", "can1 jia1", "to take part", 2],
  ["参观", "can1 guan1", "to visit (a place)", 2], ["访问", "fang3 wen4", "to visit", 2],
  ["邀请", "yao1 qing3", "to invite", 2], ["欢迎", "huan1 ying2", "welcome", 2],
  ["感谢", "gan3 xie4", "to thank", 2], ["道歉", "dao4 qian4", "to apologize", 2],
  ["原谅", "yuan2 liang4", "to forgive", 2], ["建议", "jian4 yi4", "suggestion", 2],
  ["意见", "yi4 jian4", "opinion", 2], ["同意", "tong2 yi4", "to agree", 2],
  ["反对", "fan3 dui4", "to oppose", 2], ["支持", "zhi1 chi2", "to support", 2],
  ["相信", "xiang1 xin4", "to believe", 2], ["怀疑", "huai2 yi2", "to doubt", 2],
  ["发现", "fa1 xian4", "to discover", 2], ["发生", "fa1 sheng1", "to happen", 2],
  ["变化", "bian4 hua4", "change", 2], ["改变", "gai3 bian4", "to change", 2],
  ["提高", "ti2 gao1", "to improve", 2], ["进步", "jin4 bu4", "progress", 2],
  ["成功", "cheng2 gong1", "success", 2], ["失败", "shi1 bai4", "failure", 2],
  ["困难", "kun4 nan5", "difficulty", 2], ["简单", "jian3 dan1", "simple", 2],
  ["复杂", "fu4 za2", "complicated", 2], ["特别", "te4 bie2", "special", 2],
  ["普通", "pu3 tong1", "ordinary", 2], ["一般", "yi1 ban1", "average, general", 2],

  // ---- expansion II: out and about ---------------------------------------------------
  ["遇到", "yu4 dao4", "to run into", 2], ["见面", "jian4 mian4", "to meet", 2],
  ["聊天", "liao2 tian1", "to chat", 2], ["散步", "san4 bu4", "to take a walk", 2],
  ["逛街", "guang4 jie1", "to go shopping", 2], ["约会", "yue1 hui4", "a date", 2],
  ["请客", "qing3 ke4", "to treat (pay)", 2], ["点菜", "dian3 cai4", "to order food", 2],
  ["排队", "pai2 dui4", "to queue", 2], ["出发", "chu1 fa1", "to set off", 2],
  ["到达", "dao4 da2", "to arrive", 2], ["经过", "jing1 guo4", "to pass by", 2],
  ["停车", "ting2 che1", "to park", 2], ["地址", "di4 zhi3", "address", 2],
  ["附近", "fu4 jin4", "nearby", 2], ["旁边", "pang2 bian1", "beside", 2],
  ["中间", "zhong1 jian1", "the middle", 2], ["对面", "dui4 mian4", "opposite", 2],
  ["楼上", "lou2 shang4", "upstairs", 2], ["楼下", "lou2 xia4", "downstairs", 2],
  ["门口", "men2 kou3", "doorway", 2],

  // ---- expansion II: weather and scenery ---------------------------------------------
  ["温度", "wen1 du4", "temperature", 2], ["空气", "kong1 qi4", "air", 2],
  ["风景", "feng1 jing3", "scenery", 2], ["沙滩", "sha1 tan1", "beach", 2],
  ["海边", "hai3 bian1", "seaside", 2], ["森林", "sen1 lin2", "forest", 2],
  ["沙漠", "sha1 mo4", "desert", 2], ["石头", "shi2 tou5", "stone", 2],
  ["影子", "ying3 zi5", "shadow", 2], ["声音", "sheng1 yin1", "sound, voice", 2],
  ["蓝色", "lan2 se4", "blue", 2], ["绿色", "lv4 se4", "green", 2],
  ["黄色", "huang2 se4", "yellow", 2], ["白色", "bai2 se4", "white", 2],
  ["黑色", "hei1 se4", "black", 2], ["紫色", "zi3 se4", "purple", 2],
  ["粉色", "fen3 se4", "pink", 2],

  // ---- expansion II: longer phrases ---------------------------------------------------
  ["运动员", "yun4 dong4 yuan2", "athlete", 3],
  ["乒乓球", "ping1 pang1 qiu2", "ping-pong", 3],
  ["羽毛球", "yu3 mao2 qiu2", "badminton", 3],
  ["洗衣机", "xi3 yi1 ji1", "washing machine", 3],
  ["矿泉水", "kuang4 quan2 shui3", "mineral water", 3],
  ["加油站", "jia1 you2 zhan4", "gas station", 3],
  ["红绿灯", "hong2 lv4 deng1", "traffic light", 3],
  ["差不多", "cha4 bu5 duo1", "more or less", 3],
  ["有意思", "you3 yi4 si5", "interesting", 3],
  ["没意思", "mei2 yi4 si5", "boring", 3]
];
