/* =====================================================================
   Lights Out — the rules on a picture house's marquee.

   Classic Lights Out: pressing a bulb switches it and its four
   orthogonal neighbours. Put every bulb out. Boards are generated by
   pressing random bulbs on a dark sign, so every deal is solvable;
   par is the true minimum, found by Gaussian elimination over GF(2)
   (plus the kernel enumeration, since several press-sets can solve the
   same sign).

   Modes
     windup  "Last Reel": levels with a reel of film, par + a little
             slack in moves; the run ends when it runs out; best =
             highest level closed. (The key dates from the game's first
             look, a tray of pocket watches, and stays for saved settings.)
     daily   the same seeded 5×5 for everyone; the first solve is the
             recorded, shareable result
     zen     3×3 / 5×5 / 7×7, no budget, just the clicks
   ===================================================================== */
(function () {
  "use strict";

  var A = window.LoArt;
  function $(id) { return document.getElementById(id); }
  function fx() { return !(window.RM_ON && window.RM_ON()); }
  // a button's keycap, hidden on touch-only devices (.gs-keys, motion-toggle.js)
  function keyCap(k) { return '<span class="gs-keys"><kbd>' + k + "</kbd></span>"; }
  var ENTER_CAP = " " + keyCap("Enter");

  var store = window.GameShell ? GameShell.store : {
    get: function (k, f) { try { var v = localStorage.getItem(k); return v == null ? f : v; } catch (e) { return f; } },
    getNum: function (k, f) { var v = parseFloat(this.get(k, "")); return isNaN(v) ? f : v; },
    set: function (k, v) { try { localStorage.setItem(k, v); return true; } catch (e) { return false; } },
    remove: function (k) { try { localStorage.removeItem(k); } catch (e) {} }
  };
  var bestLevel = window.GameShell ? GameShell.best("lightsout_best", { higher: true }) : null;

  // ---- the daily feature -------------------------------------------------
  var DAY0 = Date.UTC(2026, 8, 27);
  function today() {
    var d = new Date();
    var utc = Date.UTC(d.getFullYear(), d.getMonth(), d.getDate());
    var n = Math.round((utc - DAY0) / 86400000) + 1;
    var mm = ("0" + (d.getMonth() + 1)).slice(-2), dd = ("0" + d.getDate()).slice(-2);
    return { n: n, ymd: d.getFullYear() + "-" + mm + "-" + dd };
  }
  function readDaily() {
    var t = today();
    try {
      var d = JSON.parse(store.get("lightsout_daily", "null"));
      if (d && d.ymd === t.ymd) return d;
    } catch (e) {}
    return { ymd: t.ymd, n: t.n, moves: 0, par: 0, done: false };
  }
  function writeDaily(d) { store.set("lightsout_daily", JSON.stringify(d)); }
  function readZen() {
    try { var z = JSON.parse(store.get("lightsout_zen", "null")); if (z) return z; } catch (e) {}
    return {};
  }

  // ---- GF(2): the exact minimum number of presses -------------------------
  function weight(v) { var w = 0; for (var i = 0; i < v.length; i++) w += v[i]; return w; }

  function solveMin(lit, n) {
    var N = n * n, i, r, c, k;
    var rows = [];
    for (i = 0; i < N; i++) {
      var row = new Uint8Array(N + 1);
      var x = i % n, y = (i / n) | 0;
      row[i] = 1;
      if (x > 0) row[i - 1] = 1;
      if (x < n - 1) row[i + 1] = 1;
      if (y > 0) row[i - n] = 1;
      if (y < n - 1) row[i + n] = 1;
      row[N] = lit[i] ? 1 : 0;
      rows.push(row);
    }
    var pivotCol = [], rank = 0;
    for (c = 0; c < N; c++) {
      var pr = -1;
      for (r = rank; r < N; r++) if (rows[r][c]) { pr = r; break; }
      if (pr < 0) continue;
      var t = rows[rank]; rows[rank] = rows[pr]; rows[pr] = t;
      for (r = 0; r < N; r++) {
        if (r !== rank && rows[r][c]) for (k = c; k <= N; k++) rows[r][k] ^= rows[rank][k];
      }
      pivotCol[rank++] = c;
    }
    for (r = rank; r < N; r++) if (rows[r][N]) return null;   // unsolvable
    var x0 = new Uint8Array(N);
    for (r = 0; r < rank; r++) x0[pivotCol[r]] = rows[r][N];
    var isPivot = new Uint8Array(N);
    for (r = 0; r < rank; r++) isPivot[pivotCol[r]] = 1;
    var basis = [];
    for (c = 0; c < N; c++) {
      if (isPivot[c]) continue;
      var v = new Uint8Array(N); v[c] = 1;
      for (r = 0; r < rank; r++) if (rows[r][c]) v[pivotCol[r]] = 1;
      basis.push(v);
    }
    var best = x0, bw = weight(x0);
    if (basis.length && basis.length <= 10) {
      for (var m = 1; m < (1 << basis.length); m++) {
        var v2 = x0.slice();
        for (var b = 0; b < basis.length; b++) {
          if (m & (1 << b)) for (k = 0; k < N; k++) v2[k] ^= basis[b][k];
        }
        var w = weight(v2);
        if (w < bw) { bw = w; best = v2; }
      }
    }
    return { mask: best, weight: bw };
  }

  // ---- sound: switches ------------------------------------------------------
  var actx = null;
  function audio() {
    if (!actx) { var AC = window.AudioContext || window.webkitAudioContext; if (AC) actx = new AC(); }
    if (actx && actx.state === "suspended") actx.resume();
    return actx;
  }
  // a bulb's switch: a pinch of noise through a bandpass, plus a short ping,
  // lower for one going out
  function click(out) {
    var ac = audio(); if (!ac) return;
    var t0 = ac.currentTime;
    var len = Math.floor(ac.sampleRate * 0.05);
    var buf = ac.createBuffer(1, len, ac.sampleRate);
    var d = buf.getChannelData(0);
    for (var i = 0; i < len; i++) d[i] = (Math.random() * 2 - 1) * (1 - i / len);
    var src = ac.createBufferSource(); src.buffer = buf;
    var bp = ac.createBiquadFilter(); bp.type = "bandpass";
    bp.frequency.value = out ? 1700 : 2600; bp.Q.value = 2.5;
    var g = ac.createGain(); g.gain.value = out ? 0.28 : 0.18;
    src.connect(bp); bp.connect(g); g.connect(ac.destination);
    src.start(t0);
    var o = ac.createOscillator(), g2 = ac.createGain();
    o.type = "sine"; o.frequency.value = out ? 620 : 940;
    g2.gain.setValueAtTime(0.06, t0);
    g2.gain.exponentialRampToValueAtTime(0.0001, t0 + 0.09);
    o.connect(g2); g2.connect(ac.destination);
    o.start(t0); o.stop(t0 + 0.1);
  }
  function bell(freq, at, vol) {
    var ac = audio(); if (!ac) return;
    var t0 = ac.currentTime + at;
    [1, 2.76, 5.4].forEach(function (h, i) {
      var o = ac.createOscillator(), g = ac.createGain();
      o.type = "sine"; o.frequency.value = freq * h;
      var v = (vol || 0.14) / (i + 1) / 1.6;
      g.gain.setValueAtTime(v, t0);
      g.gain.exponentialRampToValueAtTime(0.0001, t0 + 1.1 - i * 0.25);
      o.connect(g); g.connect(ac.destination);
      o.start(t0); o.stop(t0 + 1.2);
    });
  }
  function chime() { bell(660, 0); bell(831, 0.18); bell(1108, 0.36, 0.12); }
  function runOut() {
    var ac = audio(); if (!ac) return;
    var t0 = ac.currentTime;
    var o = ac.createOscillator(), g = ac.createGain();
    o.type = "triangle";
    o.frequency.setValueAtTime(240, t0);
    o.frequency.exponentialRampToValueAtTime(70, t0 + 0.7);
    g.gain.setValueAtTime(0.16, t0);
    g.gain.exponentialRampToValueAtTime(0.0001, t0 + 0.75);
    o.connect(g); g.connect(ac.destination);
    o.start(t0); o.stop(t0 + 0.8);
  }

  // ---- state ----------------------------------------------------------------
  var state = "menu";                 // menu | play | over
  var mode = store.get("lightsout_mode", "windup");
  if (["windup", "daily", "zen"].indexOf(mode) === -1) mode = "windup";
  var zenN = +store.get("lightsout_size", "5") || 5;
  if ([3, 5, 7].indexOf(zenN) === -1) zenN = 5;

  var n = 5, N = 25, lit = new Uint8Array(25), cells = [];
  var moves = 0, par = 0, level = 1, budget = 0, dailyRecorded = false;
  var closed = false;                 // last reel: a level just closed, its "Next level" card up
  var ranOut = false;                 // last reel: the reel ran out, its "Roll again" card up

  function levelSpec(L) {
    var t = [[3, 3], [3, 5], [4, 5], [4, 7], [5, 6], [5, 8], [5, 10], [5, 12]];
    if (L <= 8) return { n: t[L - 1][0], scr: t[L - 1][1] };
    return { n: 5, scr: Math.min(16, 12 + (L - 8)) };
  }

  // press scr distinct bulbs on a dark sign: solvable by construction
  function generate(size, scr, rng) {
    var NN = size * size, b, tries = 0;
    do {
      b = new Uint8Array(NN);
      var order = [];
      for (var i = 0; i < NN; i++) order.push(i);
      for (var j = NN - 1; j > 0; j--) {
        var k = Math.floor(rng() * (j + 1)), t = order[j]; order[j] = order[k]; order[k] = t;
      }
      for (var p = 0; p < Math.min(scr, NN); p++) applyToggle(b, order[p], size);
      tries++;
    } while (weight(b) === 0 && tries < 20);
    return b;
  }
  function applyToggle(b, i, size) {
    var x = i % size, y = (i / size) | 0;
    b[i] ^= 1;
    if (x > 0) b[i - 1] ^= 1;
    if (x < size - 1) b[i + 1] ^= 1;
    if (y > 0) b[i - size] ^= 1;
    if (y < size - 1) b[i + size] ^= 1;
  }

  // ---- the sign ---------------------------------------------------------------
  function buildBoard() {
    var board = $("board");
    board.innerHTML = "";
    board.style.gridTemplateColumns = "repeat(" + n + ", auto)";
    cells = [];
    for (var i = 0; i < N; i++) {
      var b = document.createElement("button");
      b.type = "button";
      b.className = "bulb";
      b.setAttribute("role", "gridcell");
      b.setAttribute("aria-label", "bulb, row " + (((i / n) | 0) + 1) + " column " + ((i % n) + 1));
      b.innerHTML = A.socketSVG() + '<span class="glow"></span><span class="lit">' + A.litSVG() + "</span>";
      (function (idx) { b.addEventListener("click", function () { press(idx); }); })(i);
      board.appendChild(b);
      cells.push(b);
    }
    layout();
    paintAll(true);
  }

  // Size the bulbs to the room left under the name, the letterboard and the
  // HUD (measured: they wrap, and the web fonts change their height), then
  // run the chaser round the sign at its new size.
  function layout() {
    var vw = window.innerWidth, vh = window.innerHeight;
    var gap = Math.max(4, Math.min(12, vw / 80));
    // the chaser's border, each side: thinner on a phone, and thinner still on
    // a narrow one, where seven 42px bulbs and their chrome edge only just fit
    var frame = vw < 380 ? 10 : vw < 640 ? 13 : 18;
    // (the sign's chrome edge, a box-shadow, stands 9px outside its box)
    var top = $("head").getBoundingClientRect().bottom + 20;
    var cw = Math.min(
      (vw - 28 - frame * 2 - gap * (n - 1)) / n,
      (vh - top - 30 - frame * 2 - gap * (n - 1)) / n,
      112
    );
    cw = Math.max(42, Math.floor(cw));
    var board = $("board");
    board.style.setProperty("--gap", gap + "px");
    board.style.setProperty("--cw", cw + "px");
    board.style.setProperty("--frame", frame + "px");
    var old = board.querySelector(".chase");
    if (old) board.removeChild(old);
    board.insertAdjacentHTML("beforeend", A.chaserSVG(board.clientWidth, board.clientHeight, frame));
  }

  // sync every bulb to the state; instant on build, staggered on presses
  function paintAll(instant) {
    cells.forEach(function (c, i) { c.classList.toggle("on", !!lit[i]); });
    if (instant) void $("board").offsetWidth;
  }

  function press(i) {
    if (state !== "play") return;
    audio();
    var size = n, affected = [i];
    var x = i % size, y = (i / size) | 0;
    if (x > 0) affected.push(i - 1);
    if (x < size - 1) affected.push(i + 1);
    if (y > 0) affected.push(i - size);
    if (y < size - 1) affected.push(i + size);
    applyToggle(lit, i, size);
    moves++;
    // the chorus: the pressed bulb switches now, neighbours follow. With FX off
    // the bulbs all switch at once, but the clicks keep their ripple (five at
    // the same instant stacked into one loud click)
    var ripple = fx();
    affected.forEach(function (j, k) {
      var delay = k === 0 ? 0 : 40 + k * 34;
      setTimeout(function () { cells[j].classList.toggle("on", !!lit[j]); }, ripple ? delay : 0);
      setTimeout(function () { click(!lit[j]); }, delay);
    });
    hud();
    if (weight(lit) === 0) { win(); return; }
    if (mode === "windup" && moves >= budget) { fail(); }
  }

  function hint() {
    if (state !== "play") return;
    if (mode === "windup" && budget - moves <= 1) return;   // don't let a hint end the run
    var sol = solveMin(lit, n);
    if (!sol || !sol.weight) return;
    for (var i = 0; i < N; i++) {
      if (sol.mask[i]) {
        moves++;                                           // a hint costs one move
        hud();
        var w = cells[i];
        w.classList.remove("glint");
        void w.offsetWidth;
        w.classList.add("glint");
        // FX off holds the glint still (styles.css), so it comes off on a timer
        // once the three 0.9s glints would have finished
        clearTimeout(w.glintT);
        w.glintT = setTimeout(function () { w.classList.remove("glint"); }, 2750);
        break;
      }
    }
  }

  // ---- runs ---------------------------------------------------------------------
  function deal(size, scr, rng) {
    n = size; N = n * n;
    lit = generate(n, scr, rng || Math.random);
    var sol = solveMin(lit, n);
    par = sol ? sol.weight : scr;
    moves = 0;
    $("front").classList.remove("dark");
    buildBoard();
    hud();
  }

  function startRun(m) {
    if (m) mode = m;
    store.set("lightsout_mode", mode);
    audio();
    $("menu").hidden = true; $("over").hidden = true;
    $("hudline").hidden = false;
    $("reel").hidden = mode !== "windup";
    state = "play";
    closed = ranOut = false;
    if (mode === "windup") {
      level = 1;
      startLevel();
    } else if (mode === "daily") {
      var t = today();
      dailyRecorded = readDaily().done;
      deal(5, 12, A.mulberry(((t.n * 2654435761) >>> 0) ^ 0x77A9));
      $("sign-sub").textContent = "daily feature No. " + t.n;
    } else {
      deal(zenN, zenN === 3 ? 5 : zenN === 5 ? 11 : 19, Math.random);
      $("sign-sub").textContent = "zen · " + zenN + "×" + zenN;
    }
    hud();
  }

  function startLevel() {
    var spec = levelSpec(level);
    deal(spec.n, spec.scr, Math.random);
    budget = par + Math.max(2, Math.ceil(par * 0.4));
    $("sign-sub").textContent = "level " + level;
    state = "play";
    closed = ranOut = false;
    hud();
  }

  function hud() {
    $("hud-mode").textContent = mode === "windup" ? "last reel" : mode === "daily" ? "daily" : "zen";
    $("hud-moves").textContent = moves + (moves === 1 ? " move" : " moves");
    $("hud-par").textContent = "par " + par;
    if (mode === "windup" && state === "play") {
      var left = Math.max(0, budget - moves);
      $("reel-film").style.width = (100 * left / budget) + "%";
      $("reel-label").textContent = left + " left";
    }
  }

  function win() {
    state = "over";
    chime();
    // the last bulb out takes the name, the letterboard and the chaser with it
    $("front").classList.add("dark");
    var overParVal = moves - par;
    var lines = [];
    if (mode === "windup") {
      closed = true;
      if (bestLevel) bestLevel.submit(level);
      $("over-title").textContent = "House dark — level " + level + " closed";
      $("over-msg").textContent = moves + " moves · par " + par;
      lines.push("the reel had " + (budget - moves) + " to spare");
      lines.push("best run: level " + (bestLevel ? bestLevel.get() : level));
      $("again").innerHTML = "Next level" + ENTER_CAP;
      $("share").hidden = true;
    } else if (mode === "daily") {
      var d = readDaily();
      if (!d.done) {
        d.done = true; d.moves = moves; d.par = par;
        writeDaily(d);
        dailyRecorded = false;                    // this run WAS the record
      }
      var rec = readDaily();
      $("over-title").textContent = "Lights out";
      $("over-msg").textContent = moves + " moves · par " + par;
      lines.push("daily feature No. " + rec.n + (dailyRecorded
        ? " — recorded earlier: " + rec.moves + " moves"
        : overParVal === 0 ? " — a perfect blackout!" : ""));
      $("again").innerHTML = "Once more (just for fun)" + ENTER_CAP;
      $("share").hidden = false;
    } else {
      var z = readZen(), key = "s" + n;
      z[key] = (z[key] || 0) + 1;
      var dkey = "d" + n;
      if (z[dkey] == null || overParVal < z[dkey]) z[dkey] = overParVal;
      store.set("lightsout_zen", JSON.stringify(z));
      $("over-title").textContent = "Lights out";
      $("over-msg").textContent = moves + " moves · par " + par;
      lines.push(overParVal === 0 ? "a perfect blackout!" : "+" + overParVal + " over par");
      lines.push(n + "×" + n + " signs put out: " + z["s" + n]);
      $("again").innerHTML = "New sign" + ENTER_CAP;
      $("share").hidden = true;
    }
    $("over-stats").textContent = lines.join("\n");
    setTimeout(showOver, fx() ? 750 : 150);
  }

  function fail() {
    state = "over";
    ranOut = true;
    runOut();
    if (bestLevel) bestLevel.submit(level - 1);
    $("over-title").textContent = "The reel ran out";
    $("over-msg").textContent = "level " + level;
    $("over-stats").textContent = (level > 1 ? "closed " + (level - 1) + (level === 2 ? " level" : " levels") + " · " : "") +
      "best run: level " + (bestLevel ? bestLevel.get() : 0);
    $("again").innerHTML = "Roll again" + ENTER_CAP;
    $("share").hidden = true;
    setTimeout(showOver, 900);
  }
  // the card takes focus, so Enter is its Next / Again button and not the
  // bulb (or hint) a keyboard player last pressed
  function showOver() {
    if (state !== "over") return;
    $("over").hidden = false;
    $("again").focus({ preventScroll: true });
  }

  function shareDaily() {
    var d = readDaily();
    var text = "Lights Out · Daily feature No. " + d.n + " (" + d.ymd + ")\n" +
      "Dark in " + d.moves + " moves · par " + d.par + " 🎬\n" +
      location.origin + location.pathname;
    function copied() { $("share").textContent = "copied!"; setTimeout(function () { $("share").textContent = "Share result"; }, 1400); }
    // (the clipboard wasn't allowed: show the result to copy, in the game's own look)
    function fallback() { if (window.GameShell) GameShell.copyBox({ title: "Copy your result", text: text }); else try { window.prompt("Copy your result:", text); } catch (e) {} }
    if (navigator.share && /Mobi|Android|iPhone|iPad/.test(navigator.userAgent)) {
      navigator.share({ text: text }).catch(function (e2) { if (!e2 || e2.name !== "AbortError") fallback(); });
      return;
    }
    if (navigator.clipboard && navigator.clipboard.writeText) navigator.clipboard.writeText(text).then(copied, fallback);
    else fallback();
  }

  // ---- menu -----------------------------------------------------------------------
  function paintMenu() {
    document.querySelectorAll("#pick-mode button").forEach(function (b) {
      b.classList.toggle("on", b.getAttribute("data-v") === mode);
    });
    $("pick-size").hidden = mode !== "zen";
    document.querySelectorAll("#pick-size button").forEach(function (b) {
      b.classList.toggle("on", +b.getAttribute("data-n") === zenN);
    });
    var d = readDaily();
    $("daily-small").innerHTML = d.done
      ? "done: " + d.moves + " moves (par " + d.par + ") ✓ " + keyCap("2")
      : "today's sign, share your moves " + keyCap("2");
    var parts = [];
    if (bestLevel && bestLevel.get()) parts.push("last reel: level " + bestLevel.get());
    var z = readZen(), zp = [];
    [3, 5, 7].forEach(function (s) { if (z["s" + s]) zp.push(s + "×" + s + " " + z["s" + s]); });
    if (zp.length) parts.push("zen signs: " + zp.join(" · "));
    $("bests").textContent = parts.length ? parts.join("  ·  ") : "the house is still lit — no records yet";
  }

  function toMenu() {
    // walking away mid-run still counts the levels already closed
    if (state === "play" && mode === "windup" && level > 1 && bestLevel) bestLevel.submit(level - 1);
    state = "menu";
    closed = ranOut = false;
    $("over").hidden = true; $("hudline").hidden = true; $("reel").hidden = true;
    $("menu").hidden = false;
    $("sign-sub").textContent = "put out every bulb";
    $("front").classList.remove("dark");
    layout();
    paintMenu();
  }

  document.querySelectorAll("#pick-mode button").forEach(function (b) {
    b.addEventListener("click", function () {
      mode = b.getAttribute("data-v");
      store.set("lightsout_mode", mode);
      paintMenu();
    });
  });
  document.querySelectorAll("#pick-size button").forEach(function (b) {
    b.addEventListener("click", function () {
      zenN = +b.getAttribute("data-n");
      store.set("lightsout_size", "" + zenN);
      paintMenu();
    });
  });
  // a mouse click on a mode or size doesn't take focus (Tab still reaches it):
  // left focused, the Enter that should start the run would press it again
  document.querySelectorAll("#pick-mode button, #pick-size button").forEach(function (b) {
    b.addEventListener("mousedown", function (e) { e.preventDefault(); });
  });
  $("play").addEventListener("click", function () { startRun(mode); });
  // 4 5 6 pick Zen's board size on the menu (the keycaps are on the buttons,
  // beside the menu's other keys)
  if (window.GameShell && GameShell.menuKeys) GameShell.menuKeys({
    active: function () { return state === "menu"; },
    groups: [{ sel: "#pick-size button", keys: ["4", "5", "6"], caps: false }]
  });
  $("hint").addEventListener("click", hint);
  $("share").addEventListener("click", shareDaily);
  // back to the modes, asking first while a run would be lost (a pressed
  // sign, or a last reel's "Next level" card); the results go at once
  function askToMenu() {
    if (window.GameShell && GameShell.askQuit) GameShell.askQuit({ title: "Quit this game?", ok: "Quit" }, toMenu);
    else toMenu();
  }
  $("to-menu").addEventListener("click", askToMenu);
  $("again").addEventListener("click", function () {
    if (mode === "windup" && !ranOut) { level++; $("over").hidden = true; startLevel(); }
    else startRun(mode);
  });

  // ---- keys ------------------------------------------------------------------------
  document.addEventListener("keydown", function (e) {
    if (e.ctrlKey || e.metaKey || e.altKey) return;
    if (e.repeat) return;
    // Enter on a focused button is that button's click (a mode, Next, Modes…);
    // starting a run here as well would run both
    if (e.key === "Enter" && e.target && e.target.closest && e.target.closest("button")) return;
    if (state === "menu") {
      if (e.key === "1" || e.key === "2" || e.key === "3") {
        mode = ["windup", "daily", "zen"][+e.key - 1];
        store.set("lightsout_mode", mode);
        paintMenu();
      } else if (e.key === "Enter") startRun(mode);
      return;
    }
    // Backspace goes back to the modes, from the results or mid-sign (there's
    // no pause here), asking first mid-sign once there's something to lose;
    // Esc is left to ../motion-toggle.js, which takes it to the games page
    if (state === "over" && !$("over").hidden) {
      if (e.key === "Enter") $("again").click();
      else if (e.key === "Backspace") { e.preventDefault(); askToMenu(); }
      return;
    }
    if (state === "play") {
      if (e.key === "Backspace") { e.preventDefault(); askToMenu(); return; }
      if (e.key.toLowerCase() === "h") { hint(); return; }
      // arrows walk the sign, Enter/Space presses (native button click)
      var K = { ArrowLeft: -1, ArrowRight: 1, ArrowUp: -n, ArrowDown: n }[e.key];
      if (K != null) {
        e.preventDefault();
        var at = cells.indexOf(document.activeElement);
        if (at === -1) at = 0;
        var to = at + K;
        if (e.key === "ArrowLeft" && at % n === 0) to = at;
        if (e.key === "ArrowRight" && at % n === n - 1) to = at;
        if (to >= 0 && to < N) cells[to].focus();
      }
    }
  });

  // ---- Visual FX ---------------------------------------------------------------------
  // styles.css keys the motion off body.fxon: bulbs warm up and cool down, and
  // the chaser runs. With FX off they switch at once and the chaser holds
  // still, every bulb of it lit. Follows the ✨ switch the moment it flips.
  window.addEventListener("reducemotionchange", function () { document.body.classList.toggle("fxon", fx()); });
  document.body.classList.toggle("fxon", fx());

  // ---- leaving -----------------------------------------------------------------------
  // Leaving asks first once a sign has been pressed (or hinted), and all through
  // a last reel run past level 1, its "Next level" card included. No sign is saved
  // part-way (lightsout_zen keeps only tallies), so zen and daily signs count
  // too; the menu, a fresh sign and the results don't. There's no pause.
  if (window.GameShell && GameShell.guardLeave) GameShell.guardLeave(function () {
    if (state === "play") return moves > 0 || (mode === "windup" && level > 1);
    return state === "over" && mode === "windup" && closed;
  });

  // ---- go ---------------------------------------------------------------------------
  document.body.insertAdjacentHTML("beforeend", A.defsSVG());
  n = 5; N = 25; lit = new Uint8Array(25);
  deal(5, 11, A.mulberry(42));            // a pretty sign behind the menu
  window.addEventListener("resize", layout);
  if (document.fonts && document.fonts.ready) document.fonts.ready.then(layout);
  toMenu();

  // test hooks — the Playwright harness drives runs through these
  window.LightsOut = {
    state: function () { return state; },
    grid: function () { return Array.from(lit); },
    press: press,
    moves: function () { return moves; },
    par: function () { return par; },
    level: function () { return level; },
    budget: function () { return budget; },
    size: function () { return n; },
    solution: function () {
      var s = solveMin(lit, n), out = [];
      if (s) for (var i = 0; i < N; i++) if (s.mask[i]) out.push(i);
      return out;
    },
    start: startRun,
    toMenu: toMenu,
    daily: readDaily,
    cellRect: function (i) { return cells[i].getBoundingClientRect(); }
  };
})();
