/* =====================================================================
   24 — puzzle pool builder. Node only, NOT loaded by any page.

     node build-puzzles.js          rebuild puzzles.js
     node build-puzzles.js --check  rebuild in memory and compare

   Sorts all 1,820 hands of four card values (1-13) with solver.js:
   1,362 can make 24. Each solvable hand gets a difficulty score, the cost
   of its easiest solution (division, subtraction, fractions, negatives and
   going past 24 cost more) plus a little extra for hands with few routes.

   Pools written to puzzles.js:
     easy / medium / hard   whole-number hands by score (40% / 35% / 25%)
     tough                  the 16 hands that need fractions, plus the 100
                            hardest whole-number hands (Hard mode)
     daily                  medium + hard, shuffled once with a fixed seed

   THE DAILY LIST IS FROZEN: the puzzle for a date is daily[day number], so
   reordering or regenerating it would change past and future dailies for
   everyone. The build keeps any existing daily list as it is.
   ===================================================================== */
"use strict";
var fs = require("fs"), path = require("path");
var S = require("./solver.js");

function stepCost(op, r) {
  var c = op === "+" || op === "*" ? 1 : op === "-" ? 1.5 : 2.2;
  if (r.d !== 1) c += 4;
  if (r.n < 0) c += 2;
  if (r.d === 1 && r.n > 24) c += 1;
  return c;
}
function minCost(list) {
  var memo = {};
  function key(l) { return l.map(S.str).sort().join(","); }
  function go(l) {
    if (l.length === 1) return S.is24(l[0]) ? 0 : Infinity;
    var k = key(l);
    if (k in memo) return memo[k];
    var best = Infinity;
    for (var i = 0; i < l.length; i++) for (var j = 0; j < l.length; j++) {
      if (i === j) continue;
      var rest = l.filter(function (_, k2) { return k2 !== i && k2 !== j; });
      S.OPS.forEach(function (op) {
        var r = S.apply(l[i], op, l[j]);
        if (!r) return;
        var c = stepCost(op, r) + go(rest.concat([r]));
        if (c < best) best = c;
      });
    }
    return (memo[k] = best);
  }
  return go(list);
}

function build() {
  var rows = [];
  for (var a = 1; a <= 13; a++) for (var b = a; b <= 13; b++) for (var c = b; c <= 13; c++) for (var d = c; d <= 13; d++) {
    var l = S.fromInts([a, b, c, d]), routes = S.countRoutes(l);
    if (!routes) continue;
    rows.push({ code: S.encode([a, b, c, d]), whole: !!S.solve(l, true), score: minCost(l) + 1 / Math.sqrt(routes) });
  }
  var whole = rows.filter(function (r) { return r.whole; }).sort(function (x, y) { return x.score - y.score || (x.code < y.code ? -1 : 1); });
  var n = whole.length, e = Math.round(n * 0.4), m = Math.round(n * 0.75);
  var pools = {
    easy: whole.slice(0, e), medium: whole.slice(e, m), hard: whole.slice(m),
    tough: rows.filter(function (r) { return !r.whole; }).concat(whole.slice(n - 100)),
  };
  // A fixed-seed shuffle, so the first build's daily order is reproducible.
  var seed = 24;
  function rnd() { seed = (seed * 1103515245 + 12345) & 0x7fffffff; return seed / 0x7fffffff; }
  var daily = pools.medium.concat(pools.hard).map(function (r) { return r.code; }).sort();
  for (var i = daily.length - 1; i > 0; i--) { var j = Math.floor(rnd() * (i + 1)), t = daily[i]; daily[i] = daily[j]; daily[j] = t; }
  var out = { total: rows.length };
  Object.keys(pools).forEach(function (k) { out[k] = pools[k].map(function (r) { return r.code; }).join(" "); });
  out.daily = daily.join(" ");
  return out;
}

var FILE = path.join(__dirname, "puzzles.js");
function readExisting() {
  if (!fs.existsSync(FILE)) return null;
  var m = fs.readFileSync(FILE, "utf8").match(/daily: "([^"]*)"/);
  return m ? m[1] : null;
}
function render(p) {
  return "/* =====================================================================\n" +
    "   24 — puzzle pools. GENERATED by build-puzzles.js; edit that, not this.\n\n" +
    "   Each hand is four characters: 1-9, then A=10, B=11, C=12, D=13.\n" +
    "   " + p.total + " of the 1,820 possible hands can make 24.\n\n" +
    "   The daily list is frozen: the puzzle for a date is daily[day number],\n" +
    "   so never reorder, trim or regenerate it (only append).\n" +
    "   ===================================================================== */\n" +
    "window.TwentyFourPuzzles = {\n" +
    ["easy", "medium", "hard", "tough", "daily"].map(function (k) { return "  " + k + ": \"" + p[k] + "\","; }).join("\n") +
    "\n};\n";
}

var p = build(), old = readExisting();
if (old) p.daily = old;
var text = render(p);
if (process.argv.indexOf("--check") !== -1) {
  var same = fs.existsSync(FILE) && fs.readFileSync(FILE, "utf8") === text;
  console.log(same ? "puzzles.js is up to date" : "puzzles.js differs from a fresh build");
  process.exitCode = same ? 0 : 1;
} else {
  fs.writeFileSync(FILE, text);
  ["easy", "medium", "hard", "tough", "daily"].forEach(function (k) { console.log(k.padEnd(7), p[k].split(" ").length); });
}
