/* =====================================================================
   Passport — the atlas. [iso2, name, region, family, tier]
   region: EU AS AF AM OC
   family: which lookalike drawer the flag lives in — distractors are
           pulled from the same family first, then the same region.
   tier:   1 famous · 2 known · 3 deep cuts (tours ramp through them)
   Flag art: https://flagcdn.com/{iso2}.svg
   ===================================================================== */
window.FlagData = [
  // -------- Europe ----------------------------------------------------
  ["al", "Albania", "EU", "eagle", 2],
  ["ad", "Andorra", "EU", "tri-v", 3],
  ["at", "Austria", "EU", "rw", 1],
  ["by", "Belarus", "EU", "misc", 2],
  ["be", "Belgium", "EU", "tri-v", 1],
  ["ba", "Bosnia and Herzegovina", "EU", "misc", 2],
  ["bg", "Bulgaria", "EU", "tri-h", 2],
  ["hr", "Croatia", "EU", "tri-h", 2],
  ["cy", "Cyprus", "EU", "map", 2],
  ["cz", "Czech Republic", "EU", "misc", 2],
  ["dk", "Denmark", "EU", "nordic", 1],
  ["ee", "Estonia", "EU", "tri-h", 2],
  ["fi", "Finland", "EU", "nordic", 1],
  ["fr", "France", "EU", "tri-v", 1],
  ["de", "Germany", "EU", "tri-h", 1],
  ["gr", "Greece", "EU", "stripes", 1],
  ["hu", "Hungary", "EU", "tri-h", 2],
  ["is", "Iceland", "EU", "nordic", 1],
  ["ie", "Ireland", "EU", "tri-v", 1],
  ["it", "Italy", "EU", "tri-v", 1],
  ["lv", "Latvia", "EU", "rw", 2],
  ["li", "Liechtenstein", "EU", "misc", 3],
  ["lt", "Lithuania", "EU", "tri-h", 2],
  ["lu", "Luxembourg", "EU", "tri-h", 2],
  ["mt", "Malta", "EU", "misc", 3],
  ["md", "Moldova", "EU", "tri-v", 3],
  ["mc", "Monaco", "EU", "rw", 2],
  ["me", "Montenegro", "EU", "eagle", 3],
  ["nl", "Netherlands", "EU", "tri-h", 1],
  ["mk", "North Macedonia", "EU", "sun", 2],
  ["no", "Norway", "EU", "nordic", 1],
  ["pl", "Poland", "EU", "rw", 1],
  ["pt", "Portugal", "EU", "misc", 1],
  ["ro", "Romania", "EU", "tri-v", 2],
  ["ru", "Russia", "EU", "tri-h", 1],
  ["sm", "San Marino", "EU", "misc", 3],
  ["rs", "Serbia", "EU", "tri-h", 2],
  ["sk", "Slovakia", "EU", "tri-h", 2],
  ["si", "Slovenia", "EU", "tri-h", 2],
  ["es", "Spain", "EU", "misc", 1],
  ["se", "Sweden", "EU", "nordic", 1],
  ["ch", "Switzerland", "EU", "cross", 1],
  ["ua", "Ukraine", "EU", "bicolor", 1],
  ["gb", "United Kingdom", "EU", "ensign", 1],
  ["va", "Vatican City", "EU", "misc", 3],
  ["xk", "Kosovo", "EU", "map", 3],

  // -------- Asia & Middle East ----------------------------------------
  ["af", "Afghanistan", "AS", "tri-v", 2],
  ["am", "Armenia", "AS", "tri-h", 2],
  ["az", "Azerbaijan", "AS", "crescent", 2],
  ["bh", "Bahrain", "AS", "serrated", 3],
  ["bd", "Bangladesh", "AS", "disc", 2],
  ["bt", "Bhutan", "AS", "misc", 3],
  ["bn", "Brunei", "AS", "misc", 3],
  ["kh", "Cambodia", "AS", "misc", 2],
  ["cn", "China", "AS", "stars", 1],
  ["ge", "Georgia", "AS", "cross", 2],
  ["in", "India", "AS", "tri-h", 1],
  ["id", "Indonesia", "AS", "rw", 1],
  ["ir", "Iran", "AS", "tri-h", 2],
  ["iq", "Iraq", "AS", "panarab", 2],
  ["il", "Israel", "AS", "misc", 1],
  ["jp", "Japan", "AS", "disc", 1],
  ["jo", "Jordan", "AS", "panarab", 2],
  ["kz", "Kazakhstan", "AS", "sun", 2],
  ["kw", "Kuwait", "AS", "panarab", 2],
  ["kg", "Kyrgyzstan", "AS", "sun", 3],
  ["la", "Laos", "AS", "disc", 3],
  ["lb", "Lebanon", "AS", "misc", 2],
  ["my", "Malaysia", "AS", "canton", 1],
  ["mv", "Maldives", "AS", "crescent", 3],
  ["mn", "Mongolia", "AS", "tri-v", 2],
  ["mm", "Myanmar", "AS", "star1", 2],
  ["np", "Nepal", "AS", "misc", 2],
  ["kp", "North Korea", "AS", "star1", 2],
  ["om", "Oman", "AS", "misc", 3],
  ["pk", "Pakistan", "AS", "crescent", 1],
  ["ps", "Palestine", "AS", "panarab", 2],
  ["ph", "Philippines", "AS", "misc", 1],
  ["qa", "Qatar", "AS", "serrated", 2],
  ["sa", "Saudi Arabia", "AS", "misc", 1],
  ["sg", "Singapore", "AS", "rw", 1],
  ["kr", "South Korea", "AS", "disc", 1],
  ["lk", "Sri Lanka", "AS", "misc", 2],
  ["sy", "Syria", "AS", "panarab", 2],
  ["tw", "Taiwan", "AS", "canton", 2],
  ["tj", "Tajikistan", "AS", "tri-h", 3],
  ["th", "Thailand", "AS", "stripes", 1],
  ["tl", "East Timor", "AS", "misc", 3],
  ["tm", "Turkmenistan", "AS", "misc", 3],
  ["tr", "Turkey", "AS", "crescent", 1],
  ["ae", "United Arab Emirates", "AS", "panarab", 1],
  ["uz", "Uzbekistan", "AS", "crescent", 2],
  ["vn", "Vietnam", "AS", "star1", 1],
  ["ye", "Yemen", "AS", "panarab", 2],

  // -------- Africa -----------------------------------------------------
  ["dz", "Algeria", "AF", "crescent", 2],
  ["ao", "Angola", "AF", "misc", 2],
  ["bj", "Benin", "AF", "panafr", 3],
  ["bw", "Botswana", "AF", "bicolor", 3],
  ["bf", "Burkina Faso", "AF", "star1", 3],
  ["bi", "Burundi", "AF", "misc", 3],
  ["cv", "Cape Verde", "AF", "stars", 3],
  ["cm", "Cameroon", "AF", "panafr", 2],
  ["cf", "Central African Republic", "AF", "misc", 3],
  ["td", "Chad", "AF", "tri-v", 3],
  ["km", "Comoros", "AF", "crescent", 3],
  ["cg", "Republic of the Congo", "AF", "panafr", 3],
  ["cd", "DR Congo", "AF", "misc", 2],
  ["ci", "Ivory Coast", "AF", "tri-v", 2],
  ["dj", "Djibouti", "AF", "star1", 3],
  ["eg", "Egypt", "AF", "panarab", 1],
  ["gq", "Equatorial Guinea", "AF", "misc", 3],
  ["er", "Eritrea", "AF", "misc", 3],
  ["sz", "Eswatini", "AF", "misc", 3],
  ["et", "Ethiopia", "AF", "panafr", 2],
  ["ga", "Gabon", "AF", "tri-h", 3],
  ["gm", "Gambia", "AF", "tri-h", 3],
  ["gh", "Ghana", "AF", "panafr", 2],
  ["gn", "Guinea", "AF", "tri-v", 3],
  ["gw", "Guinea-Bissau", "AF", "panafr", 3],
  ["ke", "Kenya", "AF", "misc", 1],
  ["ls", "Lesotho", "AF", "misc", 3],
  ["lr", "Liberia", "AF", "canton", 3],
  ["ly", "Libya", "AF", "crescent", 2],
  ["mg", "Madagascar", "AF", "misc", 2],
  ["mw", "Malawi", "AF", "sun", 3],
  ["ml", "Mali", "AF", "panafr", 2],
  ["mr", "Mauritania", "AF", "crescent", 3],
  ["mu", "Mauritius", "AF", "stripes", 3],
  ["ma", "Morocco", "AF", "star1", 1],
  ["mz", "Mozambique", "AF", "misc", 3],
  ["na", "Namibia", "AF", "misc", 3],
  ["ne", "Niger", "AF", "disc", 3],
  ["ng", "Nigeria", "AF", "tri-v", 1],
  ["rw", "Rwanda", "AF", "sun", 3],
  ["st", "São Tomé and Príncipe", "AF", "panafr", 3],
  ["sn", "Senegal", "AF", "panafr", 2],
  ["sc", "Seychelles", "AF", "misc", 3],
  ["sl", "Sierra Leone", "AF", "tri-h", 3],
  ["so", "Somalia", "AF", "star1", 2],
  ["za", "South Africa", "AF", "misc", 1],
  ["ss", "South Sudan", "AF", "misc", 3],
  ["sd", "Sudan", "AF", "panarab", 2],
  ["tz", "Tanzania", "AF", "misc", 2],
  ["tg", "Togo", "AF", "star1", 3],
  ["tn", "Tunisia", "AF", "crescent", 2],
  ["ug", "Uganda", "AF", "misc", 3],
  ["zm", "Zambia", "AF", "misc", 3],
  ["zw", "Zimbabwe", "AF", "misc", 2],

  // -------- Americas ----------------------------------------------------
  ["ag", "Antigua and Barbuda", "AM", "sun", 3],
  ["ar", "Argentina", "AM", "blueband", 1],
  ["bs", "Bahamas", "AM", "misc", 3],
  ["bb", "Barbados", "AM", "tri-v", 3],
  ["bz", "Belize", "AM", "misc", 3],
  ["bo", "Bolivia", "AM", "tri-h", 2],
  ["br", "Brazil", "AM", "misc", 1],
  ["ca", "Canada", "AM", "misc", 1],
  ["cl", "Chile", "AM", "star1", 1],
  ["co", "Colombia", "AM", "tri-h", 1],
  ["cr", "Costa Rica", "AM", "stripes", 2],
  ["cu", "Cuba", "AM", "star1", 1],
  ["dm", "Dominica", "AM", "cross", 3],
  ["do", "Dominican Republic", "AM", "cross", 2],
  ["ec", "Ecuador", "AM", "tri-h", 2],
  ["sv", "El Salvador", "AM", "blueband", 2],
  ["gd", "Grenada", "AM", "misc", 3],
  ["gt", "Guatemala", "AM", "blueband", 2],
  ["gy", "Guyana", "AM", "misc", 3],
  ["ht", "Haiti", "AM", "bicolor", 2],
  ["hn", "Honduras", "AM", "blueband", 2],
  ["jm", "Jamaica", "AM", "misc", 1],
  ["mx", "Mexico", "AM", "tri-v", 1],
  ["ni", "Nicaragua", "AM", "blueband", 3],
  ["pa", "Panama", "AM", "misc", 2],
  ["py", "Paraguay", "AM", "rw", 2],
  ["pe", "Peru", "AM", "tri-v", 1],
  ["kn", "Saint Kitts and Nevis", "AM", "misc", 3],
  ["lc", "Saint Lucia", "AM", "misc", 3],
  ["vc", "Saint Vincent and the Grenadines", "AM", "misc", 3],
  ["sr", "Suriname", "AM", "star1", 3],
  ["tt", "Trinidad and Tobago", "AM", "misc", 2],
  ["us", "United States", "AM", "canton", 1],
  ["uy", "Uruguay", "AM", "canton", 2],
  ["ve", "Venezuela", "AM", "tri-h", 2],

  // -------- Oceania ------------------------------------------------------
  ["au", "Australia", "OC", "ensign", 1],
  ["fj", "Fiji", "OC", "ensign", 2],
  ["ki", "Kiribati", "OC", "sun", 3],
  ["mh", "Marshall Islands", "OC", "misc", 3],
  ["fm", "Micronesia", "OC", "stars", 3],
  ["nr", "Nauru", "OC", "misc", 3],
  ["nz", "New Zealand", "OC", "ensign", 1],
  ["pw", "Palau", "OC", "disc", 3],
  ["pg", "Papua New Guinea", "OC", "misc", 3],
  ["ws", "Samoa", "OC", "canton", 3],
  ["sb", "Solomon Islands", "OC", "misc", 3],
  ["to", "Tonga", "OC", "cross", 3],
  ["tv", "Tuvalu", "OC", "ensign", 3],
  ["vu", "Vanuatu", "OC", "misc", 3]
];
