/*
 * Tile Maze - level definitions.
 * Each grid row must be the same length. See engine.js for the tile legend.
 * Levels 1-8 are a deliberate tutorial onramp (one mechanic at a time);
 * levels 9+ are ordered by DIFFICULTY (see analyze.js, not just move count).
 */
(function (root, factory) {
  const mod = factory();
  if (typeof module !== "undefined" && module.exports) module.exports = mod;
  if (typeof window !== "undefined") window.LEVELS = mod;
})(this, function () {
  "use strict";

  return [
    // ---------------- Tutorial (1-8) ----------------
    {
      name: "First Steps",
      hint: "Reach the goal. Red tiles are walls. Green tiles make a sound.",
      grid: [
        "rrrrrr",
        "rSppgr",
        "rrrrpr",
        "rXgppr",
        "rrrrrr",
      ],
    },
    {
      name: "Live Wires",
      hint: "Yellow tiles throw you back where you came from. Go around them.",
      grid: [
        "rrrrrrr",
        "rSpypXr",
        "rppyppr",
        "rpppppr",
        "rrrrrrr",
      ],
    },
    {
      name: "Slippery Slope",
      hint: "Purple tiles are ice: you slide until you hit a wall. Plan your stops.",
      grid: [
        "rrrrrrrr",
        "rSuuuuur",
        "rrrrrrur",
        "ruuuuuur",
        "rurrrrrr",
        "ruuuuuXr",
        "rrrrrrrr",
      ],
    },
    {
      name: "Calm Waters",
      hint: "Blue water is harmless while you are Plain. Wade across.",
      grid: [
        "rrrrrrr",
        "rSbbrrr",
        "rrrbrrr",
        "rrrbbXr",
        "rrrrrrr",
      ],
    },
    {
      name: "Electric Eel",
      hint: "Blue next to yellow is electrified and bounces you. Find the dry path.",
      grid: [
        "rrrrrrrr",
        "rSppypXr",
        "rbbbbbbr",
        "rbbbbbbr",
        "rpypppyr",
        "rrrrrrrr",
      ],
    },
    {
      name: "Citrus Trap",
      hint: "Orange tiles flavor you 'Orange', which electrifies ALL blue. Stay Plain.",
      grid: [
        "rrrrrrrr",
        "rSpobbXr",
        "rppppppr",
        "rrrrrrrr",
      ],
    },
    {
      name: "Flavor Swap",
      hint: "Stuck as Orange? Purple ice re-flavors you 'Lemon', calming the water.",
      grid: [
        "rrrrrrrr",
        "rSoubbXr",
        "rrrrrrrr",
      ],
    },
    {
      name: "Cooling Off",
      hint: "Orange flavor electrifies the water to the goal. Find ice to cool off first.",
      grid: [
        "rrrrrrrrr",
        "rSpgobbXr",
        "rrrruprrr",
        "rrrrpprrr",
        "rrrrrrrrr",
      ],
    },

    // ---------------- Main game (9+), by difficulty ----------------
    {
      name: "The High Dive",
      hint: "Sliding up ends at a live tile — and its kick drops you exactly one rung back. Use it.",
      grid: [
        "rrrrrrrr",
        "rrryrrrr",
        "rrrupXrr",
        "rrrurrrr",
        "rrrurrrr",
        "rrrSrrrr",
        "rrrrrrrr",
      ],
    },
    {
      name: "Marco Polo",
      hint: "Four arms off the middle of the pool. The speakers call from the only calm one.",
      grid: [
        "rrrrrrrrrrrrr",
        "rrrrrbbbrrrrr",
        "rrrrrbybrrrrr",
        "rbbbrpbprbbXr",
        "rbybpbSbpgggr",
        "rbbbrpbprbbbr",
        "rrrrrbgbrrrrr",
        "rrrrrbbbrrrrr",
        "rrrrrrrrrrrrr",
      ],
    },
    {
      name: "The Flume",
      hint: "One long ride. Push off and let the flume carry you — seven shoves, start to splash.",
      grid: [
        "rrrrrrrrrrrrrrr",
        "rSuuuuuuuuuuuur",
        "rrrrrrrrrrrrrur",
        "ruuuuuuuuuuuuur",
        "rurrrrrrrrrrrrr",
        "ruuuuuuuuuuuuur",
        "rrrrrrrrrrrrrur",
        "ruuuuuuuuuuuXur",
        "rrrrrrrrrrrrrrr",
      ],
    },
    {
      name: "Corkscrew",
      hint: "A spiral of ice. Every push slides you to the next bend — until the bends run out.",
      grid: [
        "rrrrrrrrrrrrr",
        "rSuuuuuuuuuur",
        "rrrrrrrrrrrur",
        "ruuuuuuuuurur",
        "rurXrrrrrurur",
        "ruruuuuuuurur",
        "rurrrrrrrrrur",
        "ruuuuuuuuuuur",
        "rrrrrrrrrrrrr",
      ],
    },
    {
      name: "Frozen Lake",
      hint: "A longer ice run. Each slide ends at a wall — chain them to the goal.",
      grid: [
        "rrrrrrrr",
        "rSuuruur",
        "ruuuuuur",
        "rurruuur",
        "rruuuurr",
        "ruuuuuur",
        "ruuruuXr",
        "rrrrrrrr",
      ],
    },
    {
      name: "Static Shock",
      hint: "A wide pool. Stay clear of water touching yellow — it's live.",
      grid: [
        "rrrrrrrrr",
        "rSbbybbyr",
        "rbbbbbbbr",
        "rbbbbbbbr",
        "rbbbbbbbr",
        "rbybbbyXr",
        "rrrrrrrrr",
      ],
    },
    {
      name: "Belly Flop",
      hint: "Every run ends in a smack. Each smack bounces you back to the tile with a way onward.",
      grid: [
        "rrrrrrrrrrrrrrr",
        "rSuuuuuuuuuuuyr",
        "rrrrrrrrrrrrurr",
        "ryuuuuuuuuuuurr",
        "rrurrrrrrrrrrrr",
        "rruuuuuuuuuuuyr",
        "rrrrrrrrrrrrurr",
        "rrrrrrrrrrrXurr",
        "rrrrrrrrrrrrrrr",
      ],
    },
    {
      name: "Bitter Crossing",
      hint: "Orange flavor turns ALL water live. Reach the goal without tasting orange.",
      grid: [
        "rrrrrrrr",
        "rSbobbor",
        "rbobbbbr",
        "rbbbobbr",
        "robobbXr",
        "rrrrrrrr",
      ],
    },
    {
      name: "Mirror Pools",
      hint: "Twin pools, twin routes. Only one is truly calm — read the water, then commit.",
      grid: [
        "rrrrrrrrrrrrr",
        "rrrrrrXrrrrrr",
        "rrbbybpbbbbrr",
        "rrbbbbrbbbbrr",
        "rrbbbbrbbbbrr",
        "rrbbbbrbbbbrr",
        "rrrpbbrbbprrr",
        "rrrrpbrbprrrr",
        "rrrrrpSprrrrr",
        "rrrrrrrrrrrrr",
      ],
    },
    {
      name: "Splashdown",
      hint: "Calm water stops a slide with a splash. Live water refuses — and kicks you back onto the ice.",
      grid: [
        "rrrrrrrrrrrr",
        "rSuuuuuuuubr",
        "rrrrrrrrrrpr",
        "rybuuuuuuupr",
        "rrrXrrrrrrrr",
        "rrrrrrrrrrrr",
      ],
    },
    {
      name: "The Grotto",
      hint: "A quiet cave pool. Two eels patrol it — the water they touch is always live.",
      grid: [
        "....rrrrr....",
        "..rrrpbprrr..",
        ".rrbbbybbbrr.",
        "rrbSbbbbbpbrr",
        "rbbrbbbbrbbbr",
        "rbbbbbbrbbXbr",
        ".rbpbbybbbbr.",
        "..rrbbbbrrr..",
        "....rrrrr....",
      ],
    },
    {
      name: "Glacier",
      hint: "A bigger frozen field. Plan the whole route before you push off.",
      grid: [
        "rrrrrrrrr",
        "rSuuuuuur",
        "ruuuuurrr",
        "rruuuuuur",
        "ruuuurrur",
        "rurururrr",
        "ruuuuruur",
        "ruuruuuXr",
        "rrrrrrrrr",
      ],
    },
    {
      name: "Crossed Wires",
      hint: "More eels in the water. Trace a path that never touches a live tile.",
      grid: [
        "rrrrrrrrr",
        "rSbbbbbbr",
        "rbbbbbbbr",
        "rbybybbbr",
        "rybbbbbbr",
        "rbbbbbbyr",
        "rybbbbbXr",
        "rrrrrrrrr",
      ],
    },
    {
      name: "Lazy River",
      hint: "The river carries you corner to corner. One sticky stop lets you reach the shore seat.",
      grid: [
        "rrrrrrrrrrrrrrr",
        "rSuuuuuuuuuuurr",
        "rrrrrrrrrrrrurr",
        "rrrXprrrrrrrurr",
        "rrrrprrrrrrrurr",
        "rrrrouuuuuuuurr",
        "rrrrrrrrrrrrrrr",
      ],
    },
    {
      name: "Sampler",
      hint: "A little of every tile. Read the board before you commit to a step.",
      grid: [
        "rrrrrrr",
        "rSpryrr",
        "ruprprr",
        "rupppbr",
        "rgprppr",
        "rurypXr",
        "rrrrrrr",
      ],
    },
    {
      name: "Follow the Music",
      hint: "The speakers mark the calm water. Stray from the melody and the pool bites.",
      grid: [
        "rrrrrrrrrrrrr",
        "rSgbbybbbbbXr",
        "rbgbbbbybgbgr",
        "rybgbbybbgybr",
        "rbbbgggbbgbbr",
        "rybbbbygbbbyr",
        "rbbybbbbybbbr",
        "rrrrrrrrrrrrr",
      ],
    },
    {
      name: "Wave Pool",
      hint: "Crests are live, troughs are calm — and the floats only line up if you ride the rhythm.",
      grid: [
        "rrrrrrrrrrrrr",
        "rSpbbbbbbbbbr",
        "ryypyyyyyyyyr",
        "rbbpppppbbbbr",
        "ryyyyyypyyyyr",
        "rbbbbbpppppbr",
        "ryyyyyyyyypyr",
        "rbbbbbbbbbpXr",
        "rrrrrrrrrrrrr",
      ],
    },
    {
      name: "Flypaper",
      hint: "Walls stop you one tile short. An orange tile is sticky — slide onto it to stop exactly there.",
      grid: [
        "rrrrrrrrr",
        "rSuuuouur",
        "rrrrrurrr",
        "rrXbbprrr",
        "rrrrrrrrr",
      ],
    },
    {
      name: "Crosscurrents",
      hint: "A vast electrified lake. Only one dry channel reaches the far shore.",
      grid: [
        "rrrrrrrrrr",
        "rSbbbbbbbr",
        "rbbybbbbbr",
        "rbbbbbbbbr",
        "rbbbbbybbr",
        "rbbbbbbbbr",
        "rbbyybbbbr",
        "rybbbbbbXr",
        "rrrrrrrrrr",
      ],
    },
    {
      name: "Deep Freeze",
      hint: "The hardest ice yet. Dead-end slides will strand you — think ahead.",
      grid: [
        "rrrrrrrrrr",
        "rSuuruuuur",
        "ruuuuuurur",
        "ruuruururr",
        "rrruururur",
        "ruuururuur",
        "ruuruuuuur",
        "ruuuuruuXr",
        "rrrrrrrrrr",
      ],
    },
    {
      name: "Brackish",
      hint: "Everything mixes here: live water, poison, and ice all at once.",
      grid: [
        "rrrrrrrrr",
        "rSbpbybbr",
        "rbbybobbr",
        "rbbbbpbor",
        "rbopbbpbr",
        "rbbbpybXr",
        "rrrrrrrrr",
      ],
    },
    {
      name: "Riptide",
      hint: "A long, tall current. Live tiles lurk on every row — pick your line carefully.",
      grid: [
        "rrrrrrrrr",
        "rSbybbbbr",
        "rbbbbbbbr",
        "rbbbbbbbr",
        "rbbbbybbr",
        "ryyybbbbr",
        "rbybbbbbr",
        "rbbbbbbyr",
        "rbbbbbbXr",
        "rrrrrrrrr",
      ],
    },
    {
      name: "Infinity Edge",
      hint: "Ride the rim of the pool. Only one sticky spot on the whole edge lets you step off it.",
      grid: [
        "rrrrrrrrrrrrr",
        "ruuuuuouuuuur",
        "rurrrrXrrrrur",
        "rurppprppprur",
        "rurpppppSprur",
        "rurppprppprur",
        "rurrrprrrrrur",
        "ruuuuuuuuuuur",
        "rrrrrrrrrrrrr",
      ],
    },
    {
      name: "Crossroads",
      hint: "You'll arrive Orange, so every water arm is live. Only the arm with ice lets you cool off and pass.",
      grid: [
        "rrrrrrrrr",
        "rrrrXrrrr",
        "rrrrbrrrr",
        "rrrrurrrr",
        "rbbbpbbbr",
        "rrrrprrrr",
        "rrrrorrrr",
        "rrrrprrrr",
        "rrrrSrrrr",
        "rrrrrrrrr",
      ],
    },
    {
      name: "Poison Pools",
      hint: "Orange everywhere. Thread the safe water, using ice to wash off a bad taste.",
      grid: [
        "rrrrrrrrrr",
        "rSbobboobr",
        "rpoobbbbpr",
        "rbbobboopr",
        "rpbbpbobbr",
        "rbpbbbobbr",
        "rubbbbobXr",
        "rrrrrrrrrr",
      ],
    },
    {
      name: "Poolside Pinball",
      hint: "Orange pegs are the only brakes on this rink — but every stop sours the water below.",
      grid: [
        "rrrrrrrrrrrrr",
        "rSuuuuuouuuur",
        "ruuouuuuuuuur",
        "ruuuuuuuuuuor",
        "ruuuuuuuuuuur",
        "ruuuouuuuuuur",
        "rrrrurrrrrrrr",
        "rrrrpppppbXrr",
        "rrrrrrrrrrrrr",
      ],
    },
    {
      name: "Patchwork",
      hint: "A patchwork of every tile. Watch your flavor as you weave through.",
      grid: [
        "rrrrrrrr",
        "rSurpgur",
        "ropopbur",
        "ryyrrgpr",
        "rpgpbrbr",
        "rpuyooXr",
        "rrrrrrrr",
      ],
    },
    {
      name: "Swim-Up Bar",
      hint: "The straight line to the bar goes past the juice. Don't — orange flavor turns the pool on you.",
      grid: [
        "rrrrrrrrrrr",
        "rrrrrrXrrrr",
        "rrrrrrbrrrr",
        "rSpppoppprr",
        "rprrrrrrprr",
        "rpppupppprr",
        "rrrrrrrrrrr",
      ],
    },
    {
      name: "Tide Pools",
      hint: "Orange poison and patches of ice. If you get flavored, find ice to reset.",
      grid: [
        "rrrrrrrrr",
        "rSbobbbor",
        "rbobbbbbr",
        "robbobobr",
        "rouuobbbr",
        "rbboobbXr",
        "rrrrrrrrr",
      ],
    },
    {
      name: "Twin Flumes",
      hint: "Two flumes, one swimmer. Sticky stops and live kicks are the only rungs between them.",
      grid: [
        "rrrrrrrrr",
        "rryrrryrr",
        "rrurrruXr",
        "rrpppporr",
        "rrurrrurr",
        "rrurrrurr",
        "rropppurr",
        "rrurrrrrr",
        "rrurrrrrr",
        "rrSrrrrrr",
        "rrrrrrrrr",
      ],
    },
    {
      name: "Checkout Time",
      hint: "The exit is right there — behind water that is live no matter what. Go the long way round.",
      grid: [
        "rrrrrrrrrrrrr",
        "rSbyXpppppppr",
        "rprrrrrrrrrpr",
        "rprrryrrrrrpr",
        "rppppbppppppr",
        "rrrrprrrprrrr",
        "rrrrppppprrrr",
        "rrrrrrrrrrrrr",
      ],
    },
    {
      name: "Kiddie Pool",
      hint: "Barely six tiles across. It will still take you longer than the big pools.",
      grid: [
        "rrrrrrrr",
        "rSyubpur",
        "rupoyubr",
        "rbyupbyr",
        "rpuboXur",
        "ruypbupr",
        "rrrrrrrr",
      ],
    },
    {
      name: "Reset Button",
      hint: "Forced orange? Dip into purple ice to cool back to Lemon — twice.",
      grid: [
        "rrrrrrrrrrr",
        "rSpobbobbXr",
        "rrrupruprrr",
        "rrrpprpprrr",
        "rrrrrrrrrrr",
      ],
    },
    {
      name: "Medley",
      hint: "A medley of mechanics — one wrong flavor and the water turns on you.",
      grid: [
        "rrrrrrrrr",
        "rSpurppur",
        "rgorgoppr",
        "ruybuoror",
        "robupppor",
        "rugprpyor",
        "ruprroobr",
        "rpgybypXr",
        "rrrrrrrrr",
      ],
    },
    {
      name: "Cabana Row",
      hint: "Juice, gate, juice, gate. Duck into an icy cabana after each sip, or the gates bite.",
      grid: [
        "rrrrrrrrrrrrrrr",
        "rrrurrrrrrurrrr",
        "rSopppbppopbbXr",
        "rrrrrrrrrrrrrrr",
      ],
    },
    {
      name: "Night Swim",
      hint: "The pool after dark. Every step looks the same — almost none of them are safe.",
      grid: [
        "rrrrrrrr",
        "rSubyubr",
        "ryobuopr",
        "rbuguobr",
        "rubuybXr",
        "rrrrrrrr",
      ],
    },
    {
      name: "Kaleidoscope",
      hint: "Every color is in play. Find a clean route through the chaos.",
      grid: [
        "rrrrrrrrr",
        "rSpybroyr",
        "rgypyprbr",
        "rubpuupbr",
        "rpopobyrr",
        "rbbbbopur",
        "rybpurpXr",
        "rrrrrrrrr",
      ],
    },
    {
      name: "Spectrum",
      hint: "The full spectrum of tiles. Stay alert on every single step.",
      grid: [
        "rrrrrrrrrr",
        "rSyypppgbr",
        "rpbrpuygpr",
        "ropourpppr",
        "rgrpbyyobr",
        "rprygubror",
        "rbrbprpbor",
        "rybugpbuXr",
        "rrrrrrrrrr",
      ],
    },
    {
      name: "Pandemonium",
      hint: "All seven tile types, densely packed. Pure, unfiltered puzzle.",
      grid: [
        "rrrrrrrrrr",
        "rSprypbopr",
        "rogrrrggrr",
        "rgbrpbpbur",
        "rbpyupppor",
        "roorupyrpr",
        "rpprprurpr",
        "ryggpyrpXr",
        "rrrrrrrrrr",
      ],
    },
    {
      name: "Mosaic",
      hint: "Water, ice, poison and walls all woven together. Pick your tiles.",
      grid: [
        "rrrrrrrrr",
        "rSpobpgor",
        "rbgpobopr",
        "rruygpyur",
        "rbpouuypr",
        "rpurpyypr",
        "rporyrpXr",
        "rrrrrrrrr",
      ],
    },
    {
      name: "Grand Finale",
      hint: "The whole resort: walls, live water, poison, and ice. Good luck.",
      grid: [
        "rrrrrrrrrr",
        "rSyoubbbbr",
        "rbuyuopbbr",
        "rpubbpbbbr",
        "rbobbuybbr",
        "rbbbyuoppr",
        "rbubbobubr",
        "rbbbbbbyXr",
        "rrrrrrrrrr",
      ],
    },
    {
      name: "Kitchen Sink",
      hint: "Everything but the kitchen sink — actually, that's in here too.",
      grid: [
        "rrrrrrrrrrr",
        "rSubboyrgrr",
        "rbrpoprogbr",
        "ruobgbuuryr",
        "rbyuoroprpr",
        "robyyyobygr",
        "rboopppppbr",
        "rpupprbgbXr",
        "rrrrrrrrrrr",
      ],
    },
    {
      name: "Magnum Opus",
      hint: "The ultimate gauntlet. Master every tile to escape the resort for good.",
      grid: [
        "rrrrrrrrrrr",
        "rSpbbopbbbr",
        "rbbbbbobour",
        "rbbbybbbobr",
        "rbbybbobobr",
        "rbbbbbbuubr",
        "rbpbbbbbbyr",
        "rbbbubyubXr",
        "rrrrrrrrrrr",
      ],
    },
    {
      name: "The Deep End",
      hint: "Every brake in the book: sticky stops, live kicks, soft landings. The last length is earned.",
      grid: [
        "rrrrrrrrrrrrrrr",
        "rSuuuouuuuuuuyr",
        "rrrrrrrrrrrrurr",
        "rruuuouuuuuuurr",
        "rrurrrrrrrrrrrr",
        "rruuuuuuuuuubrr",
        "rrrrrrrrrrrrbrr",
        "rrpuoppuuuuubrr",
        "rrprrrrrrrrrrrr",
        "rrpbbpuuuuuuuXr",
        "rrrrrrrrrrrrrrr",
      ],
    },
    {
      name: "Tangle",
      hint: "Walls everywhere and every tile in play. Survival demands precision.",
      grid: [
        "rrrrrrrrrrr",
        "rSpyrporpur",
        "rpoopbuoppr",
        "rbpgoouppgr",
        "rprybypbyyr",
        "rpbyppgppor",
        "rpgrpbggbgr",
        "rrrpppyppXr",
        "rrrrrrrrrrr",
      ],
    },
    {
      name: "Labyrinth",
      hint: "A true labyrinth. Map your flavor changes before you commit to a move.",
      grid: [
        "rrrrrrrrrrr",
        "rSpyrbopuur",
        "rbgpogypgor",
        "rbbybggypbr",
        "rbpbrppbbpr",
        "rpbopppbrpr",
        "rgyugbrrppr",
        "rupbrpgryXr",
        "rrrrrrrrrrr",
      ],
    },
    {
      name: "Quagmire",
      hint: "Sticky going. Poison and live water press in from all sides.",
      grid: [
        "rrrrrrrrrrr",
        "rSobguppyur",
        "rbpbpprpogr",
        "ryobpbybgpr",
        "ryuopbbyobr",
        "ruybybgrygr",
        "rrrppubyupr",
        "roobprpppyr",
        "rrobrobpoXr",
        "rrrrrrrrrrr",
      ],
    },
    {
      name: "Maelstrom",
      hint: "Chaos in every direction. One safe thread runs through it.",
      grid: [
        "rrrrrrrrrrr",
        "rSypbbbbpyr",
        "rpobpuoubpr",
        "rupuypbyogr",
        "rppbpryrrur",
        "ryprropuogr",
        "ruoobropypr",
        "rrrbpgbbbyr",
        "rgbyruupgXr",
        "rrrrrrrrrrr",
      ],
    },
    {
      name: "Tempest",
      hint: "A storm of tiles. Read three moves ahead or get swept back.",
      grid: [
        "rrrrrrrrrrrr",
        "rSbyrbpybppr",
        "rprpyoboopur",
        "rubgrbbprbpr",
        "rgoruprrgopr",
        "rrppppruggrr",
        "rrpyrrbpbrpr",
        "rgupubypopor",
        "rpruruyoupXr",
        "rrrrrrrrrrrr",
      ],
    },
    {
      name: "Cataclysm",
      hint: "Brutal. Nearly every step risks a bounce or the wrong flavor.",
      grid: [
        "rrrrrrrrrrrrr",
        "rSpypuppopbpr",
        "rupobrpururrr",
        "ryyurrgypbrbr",
        "rpgubopbbpyur",
        "rpopbpprropyr",
        "roypyrbrgprpr",
        "ryuoopbppgpgr",
        "rppygruuruopr",
        "rppouybpbryXr",
        "rrrrrrrrrrrrr",
      ],
    },
    {
      name: "Abyss",
      hint: "The abyss of the resort. Few find the line through it.",
      grid: [
        "rrrrrrrrrrrrrr",
        "rSyourpppopupr",
        "rubprbopburror",
        "rgpbopbppypoor",
        "rpboyrpbugyubr",
        "rpypygpupprbrr",
        "rgrrgpoppryppr",
        "rpgooupbrbyppr",
        "rppprbrurpopor",
        "ryorrbrybpypur",
        "rugpporprbopXr",
        "rrrrrrrrrrrrrr",
      ],
    },
    {
      name: "The Reckoning",
      hint: "The final reckoning — fifty moves of total mastery. Escape if you can.",
      grid: [
        "rrrrrrrrrrrrrrr",
        "rSobgpopppoopbr",
        "ropppboppppurur",
        "ryprbobbgpybpor",
        "ruypgorrryybpur",
        "rppboouprpbpbur",
        "rruuguprppburpr",
        "rbypybypboruppr",
        "rypuypypryprrbr",
        "rporbpburbyroor",
        "ropgpopprpoybXr",
        "rrrrrrrrrrrrrrr",
      ],
    },
  ];
});
